/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import dao.*;
import java.awt.List;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author XL
 */

public class TelaUser extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        nomeTextUsu = new javax.swing.JTextField();
        jLabelTel = new javax.swing.JLabel();
        telTextUsu = new javax.swing.JTextField();
        jLabelCel = new javax.swing.JLabel();
        celTextUsu = new javax.swing.JTextField();
        jLabelEnd = new javax.swing.JLabel();
        endTextUsu = new javax.swing.JTextField();
        jLabelNum = new javax.swing.JLabel();
        numTextUsu = new javax.swing.JTextField();
        jLabelComplemento = new javax.swing.JLabel();
        complementoTextUsu = new javax.swing.JTextField();
        jLabelMunicipio = new javax.swing.JLabel();
        municipioComboBox = new javax.swing.JComboBox<>();
        jLabelEstado = new javax.swing.JLabel();
        estadoComboBox = new javax.swing.JComboBox<>();
        jLabelCPF = new javax.swing.JLabel();
        cpfFormattedUsu = new javax.swing.JFormattedTextField();
        jLabelRG = new javax.swing.JLabel();
        rgFormattedUsu = new javax.swing.JFormattedTextField();
        jLabelOrgao = new javax.swing.JLabel();
        orgaoComboBox = new javax.swing.JComboBox<>();
        jLabelExpediçao = new javax.swing.JLabel();
        expComboBox = new javax.swing.JComboBox<>();
        jLabelSexo = new javax.swing.JLabel();
        sexoComboBox = new javax.swing.JComboBox<>();
        jLabelNasc = new javax.swing.JLabel();
        nascFormattedUsu = new javax.swing.JFormattedTextField();
        jLabelEmail = new javax.swing.JLabel();
        emailTextUsu = new javax.swing.JTextField();
        jLabelCargo = new javax.swing.JLabel();
        selecioneCargo = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpa = new javax.swing.JButton();
        senhaPasswordCad = new javax.swing.JPasswordField();
        jLabelCargo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuAtendimento = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuEdCliente = new javax.swing.JMenuItem();
        jMenuEdUsuario = new javax.swing.JMenuItem();
        jMenuEdAtendimento = new javax.swing.JMenuItem();
        jMenuExibir = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenuItem();
        jMenuExConsultaAtendimento = new javax.swing.JMenuItem();
        jMenuConsultaFuncional = new javax.swing.JMenuItem();
        jMenuConsultaCliente = new javax.swing.JMenuItem();
        jMenu3Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TelaUser");
        getContentPane().setLayout(null);

        jLabelNome.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(51, 102, 0));
        jLabelNome.setText("Nome");
        jLabelNome.setToolTipText("");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(20, 90, 50, 30);

        nomeTextUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeTextUsuMouseClicked(evt);
            }
        });
        nomeTextUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextUsuActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextUsu);
        nomeTextUsu.setBounds(20, 120, 250, 30);

        jLabelTel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelTel.setForeground(new java.awt.Color(51, 102, 0));
        jLabelTel.setText("Tel");
        jLabelTel.setToolTipText("");
        getContentPane().add(jLabelTel);
        jLabelTel.setBounds(370, 230, 50, 30);

        telTextUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTextUsuActionPerformed(evt);
            }
        });
        getContentPane().add(telTextUsu);
        telTextUsu.setBounds(370, 260, 250, 30);

        jLabelCel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelCel.setForeground(new java.awt.Color(51, 102, 0));
        jLabelCel.setText("Cel");
        jLabelCel.setToolTipText("");
        getContentPane().add(jLabelCel);
        jLabelCel.setBounds(640, 230, 50, 30);
        getContentPane().add(celTextUsu);
        celTextUsu.setBounds(640, 260, 210, 30);

        jLabelEnd.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelEnd.setForeground(new java.awt.Color(51, 102, 0));
        jLabelEnd.setText("Logradouro");
        jLabelEnd.setToolTipText("");
        getContentPane().add(jLabelEnd);
        jLabelEnd.setBounds(20, 160, 90, 40);

        endTextUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTextUsuActionPerformed(evt);
            }
        });
        getContentPane().add(endTextUsu);
        endTextUsu.setBounds(20, 190, 250, 30);

        jLabelNum.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelNum.setForeground(new java.awt.Color(51, 102, 0));
        jLabelNum.setText("Num");
        jLabelNum.setToolTipText("");
        getContentPane().add(jLabelNum);
        jLabelNum.setBounds(290, 160, 40, 40);

        numTextUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTextUsuActionPerformed(evt);
            }
        });
        getContentPane().add(numTextUsu);
        numTextUsu.setBounds(290, 190, 80, 30);

        jLabelComplemento.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelComplemento.setForeground(new java.awt.Color(51, 102, 0));
        jLabelComplemento.setText("Complemento");
        jLabelComplemento.setToolTipText("");
        getContentPane().add(jLabelComplemento);
        jLabelComplemento.setBounds(390, 160, 130, 40);
        getContentPane().add(complementoTextUsu);
        complementoTextUsu.setBounds(390, 190, 190, 30);

        jLabelMunicipio.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelMunicipio.setForeground(new java.awt.Color(51, 102, 0));
        jLabelMunicipio.setText("Municipio");
        jLabelMunicipio.setToolTipText("");
        getContentPane().add(jLabelMunicipio);
        jLabelMunicipio.setBounds(600, 160, 80, 40);

        municipioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SP", "RS", "MG", "RJ" }));
        municipioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(municipioComboBox);
        municipioComboBox.setBounds(600, 190, 80, 30);

        jLabelEstado.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(51, 102, 0));
        jLabelEstado.setText("Estado");
        jLabelEstado.setToolTipText("");
        getContentPane().add(jLabelEstado);
        jLabelEstado.setBounds(700, 160, 80, 40);

        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "São Paulo", "Rio Grande do Sul", "Minas Gerais", "Rio de Janeiro" }));
        estadoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(estadoComboBox);
        estadoComboBox.setBounds(700, 190, 160, 30);

        jLabelCPF.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(51, 102, 0));
        jLabelCPF.setText("CPF");
        jLabelCPF.setToolTipText("");
        getContentPane().add(jLabelCPF);
        jLabelCPF.setBounds(300, 90, 30, 40);

        try {
            cpfFormattedUsu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(cpfFormattedUsu);
        cpfFormattedUsu.setBounds(300, 120, 220, 30);

        jLabelRG.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelRG.setForeground(new java.awt.Color(51, 102, 0));
        jLabelRG.setText("RG");
        jLabelRG.setToolTipText("");
        getContentPane().add(jLabelRG);
        jLabelRG.setBounds(530, 100, 30, 20);

        try {
            rgFormattedUsu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(rgFormattedUsu);
        rgFormattedUsu.setBounds(530, 120, 110, 30);

        jLabelOrgao.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelOrgao.setForeground(new java.awt.Color(51, 102, 0));
        jLabelOrgao.setText("Orgão");
        jLabelOrgao.setToolTipText("");
        getContentPane().add(jLabelOrgao);
        jLabelOrgao.setBounds(650, 90, 50, 30);

        orgaoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SP", "RS", "MG", "RJ" }));
        getContentPane().add(orgaoComboBox);
        orgaoComboBox.setBounds(650, 120, 100, 30);

        jLabelExpediçao.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelExpediçao.setForeground(new java.awt.Color(51, 102, 0));
        jLabelExpediçao.setText("Expedição");
        jLabelExpediçao.setToolTipText("");
        getContentPane().add(jLabelExpediçao);
        jLabelExpediçao.setBounds(760, 90, 90, 30);

        expComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SSP", "PM", "PC", "IFP" }));
        expComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(expComboBox);
        expComboBox.setBounds(760, 120, 90, 30);

        jLabelSexo.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(51, 102, 0));
        jLabelSexo.setText("Sexo");
        jLabelSexo.setToolTipText("");
        getContentPane().add(jLabelSexo);
        jLabelSexo.setBounds(20, 230, 50, 40);

        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));
        sexoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(sexoComboBox);
        sexoComboBox.setBounds(20, 260, 130, 40);

        jLabelNasc.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelNasc.setForeground(new java.awt.Color(51, 102, 0));
        jLabelNasc.setText("Data de nascimento");
        jLabelNasc.setToolTipText("");
        getContentPane().add(jLabelNasc);
        jLabelNasc.setBounds(170, 230, 160, 40);

        try {
            nascFormattedUsu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nascFormattedUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nascFormattedUsuActionPerformed(evt);
            }
        });
        getContentPane().add(nascFormattedUsu);
        nascFormattedUsu.setBounds(170, 260, 140, 40);

        jLabelEmail.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(51, 102, 0));
        jLabelEmail.setText("Email");
        jLabelEmail.setToolTipText("");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(20, 300, 90, 30);

        emailTextUsu.setToolTipText("");
        emailTextUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextUsuActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextUsu);
        emailTextUsu.setBounds(20, 330, 250, 30);

        jLabelCargo.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelCargo.setForeground(new java.awt.Color(51, 102, 0));
        jLabelCargo.setText("Cargo");
        jLabelCargo.setToolTipText("");
        getContentPane().add(jLabelCargo);
        jLabelCargo.setBounds(290, 300, 90, 30);

        selecioneCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Gerente", "Tecnico", "Atendente" }));
        selecioneCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecioneCargoActionPerformed(evt);
            }
        });
        getContentPane().add(selecioneCargo);
        selecioneCargo.setBounds(290, 330, 250, 30);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(330, 390, 80, 23);

        jButtonLimpa.setText("Limpar");
        jButtonLimpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimpaMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonLimpa);
        jButtonLimpa.setBounds(440, 390, 90, 23);

        senhaPasswordCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPasswordCadActionPerformed(evt);
            }
        });
        getContentPane().add(senhaPasswordCad);
        senhaPasswordCad.setBounds(570, 330, 170, 30);

        jLabelCargo1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelCargo1.setForeground(new java.awt.Color(51, 102, 0));
        jLabelCargo1.setText("Senha");
        jLabelCargo1.setToolTipText("");
        getContentPane().add(jLabelCargo1);
        jLabelCargo1.setBounds(570, 300, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MASVIG_phixrUsuarioCad.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 870, 460);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
        });

        jMenu1.setText("Inicio");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenuSair.setText("Cadastros");

        jMenuCliente.setText("Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuCliente);

        jMenuUsuario.setText("Usuário");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuUsuario);

        jMenuAtendimento.setText("Atendimento");
        jMenuAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAtendimentoActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuAtendimento);

        jMenuBar1.add(jMenuSair);

        jMenuEditar.setText("Editar");

        jMenuEdCliente.setText("Cliente");
        jMenuEdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdClienteActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdCliente);

        jMenuEdUsuario.setText("Usuário");
        jMenuEdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdUsuarioActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdUsuario);

        jMenuEdAtendimento.setText("Atendimento");
        jMenuEdAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdAtendimentoActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdAtendimento);

        jMenuBar1.add(jMenuEditar);

        jMenuExibir.setText("Exibir");

        jMenuRelatorio.setText("Relatórios");
        jMenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuRelatorio);

        jMenuExConsultaAtendimento.setText("Consulta atendimento");
        jMenuExConsultaAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExConsultaAtendimentoActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuExConsultaAtendimento);

        jMenuConsultaFuncional.setText("Consulta funcional");
        jMenuConsultaFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaFuncionalActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaFuncional);

        jMenuConsultaCliente.setText("Consulta cliente");
        jMenuConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaClienteActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaCliente);

        jMenuBar1.add(jMenuExibir);

        jMenu3Sair.setText("Sair");
        jMenu3Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3SairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3Sair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(879, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextUsuActionPerformed

    private void emailTextUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextUsuActionPerformed

    private void sexoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoComboBoxActionPerformed

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseClicked
        int erro = 0;
        if (nomeTextUsu.getText().equals("") && endTextUsu.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Preencha os campos!");
            erro++;
        } 
        
        String nome = nomeTextUsu.getText();
        String tel = telTextUsu.getText();
        String cel = celTextUsu.getText();
        String end = endTextUsu.getText();
        String num = numTextUsu.getText();
        String complemento = complementoTextUsu.getText();
        String municipio = municipioComboBox.getSelectedItem().toString();
        String estado = estadoComboBox.getSelectedItem().toString();
        String cpf = cpfFormattedUsu.getText();
        String rg = rgFormattedUsu.getText();
        String orgao = orgaoComboBox.getSelectedItem().toString();
        String exp = expComboBox.getSelectedItem().toString();
        String sexo = sexoComboBox.getSelectedItem().toString();
        String nasc = nascFormattedUsu.getText();
        String email = emailTextUsu.getText();
        String cargo = selecioneCargo.getSelectedItem().toString();
        String senha = senhaPasswordCad.getText();
        
        
        
        Date data = null;
    	String dataBanco ; 
        try {
            data = (Date) new SimpleDateFormat("dd/MM/yyyy").parse(nasc);
        } catch (java.text.ParseException e) {
            System.out.println("Ocorreu um erro\n "+e);
        }
        dataBanco = new SimpleDateFormat("yyyy-MM-dd").format(data);
        

        Usuario novoUsuario = new Usuario(nome, end, complemento, municipio, estado, sexo, email, cpf, rg, dataBanco, orgao, exp, cargo, senha, tel, cel, num);
        novoUsuario.insereUsuario();
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
        nomeTextUsu.setText("");
        telTextUsu.setText("");
        celTextUsu.setText("");
        endTextUsu.setText("");
        numTextUsu.setText("");
        complementoTextUsu.setText("");
        municipioComboBox.getSelectedItem().toString();
        estadoComboBox.getSelectedItem().toString();
        cpfFormattedUsu.setText("");
        rgFormattedUsu.setText("");
        orgaoComboBox.getSelectedItem().toString();
        expComboBox.getSelectedItem().toString();
        sexoComboBox.getSelectedItem().toString();
        nascFormattedUsu.setText("");
        emailTextUsu.setText("");
        selecioneCargo.getSelectedItem().toString();
        senhaPasswordCad.setText("");
        
    }//GEN-LAST:event_jButtonSalvarMouseClicked

    private void nomeTextUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeTextUsuMouseClicked
        //nomeTextUsu.setText("");
    }//GEN-LAST:event_nomeTextUsuMouseClicked

    private void endTextUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTextUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTextUsuActionPerformed

    private void numTextUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTextUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTextUsuActionPerformed

    private void municipioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioComboBoxActionPerformed

    private void estadoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoComboBoxActionPerformed

    private void expComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expComboBoxActionPerformed

    private void selecioneCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecioneCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecioneCargoActionPerformed

    private void senhaPasswordCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPasswordCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaPasswordCadActionPerformed

    private void jButtonLimpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpaMouseClicked
        nomeTextUsu.setText("");
        telTextUsu.setText("");
        celTextUsu.setText("");
        endTextUsu.setText("");
        numTextUsu.setText("");
        complementoTextUsu.setText("");
        municipioComboBox.getSelectedItem().toString();
        estadoComboBox.getSelectedItem().toString();
        cpfFormattedUsu.setText("");
        rgFormattedUsu.setText("");
        orgaoComboBox.getSelectedItem().toString();
        expComboBox.getSelectedItem().toString();
        sexoComboBox.getSelectedItem().toString();
        nascFormattedUsu.setText("");
        emailTextUsu.setText("");
        selecioneCargo.getSelectedItem().toString();
        senhaPasswordCad.setText("");
        
    }//GEN-LAST:event_jButtonLimpaMouseClicked

    private void nascFormattedUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nascFormattedUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nascFormattedUsuActionPerformed

    private void telTextUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTextUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telTextUsuActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        new TelaInicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        new TelaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        new TelaUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAtendimentoActionPerformed
        new TelaAtendimento().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuAtendimentoActionPerformed

    private void jMenuEdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdClienteActionPerformed
        new TelaEditaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdClienteActionPerformed

    private void jMenuEdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdUsuarioActionPerformed
        new TelaEditaUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdUsuarioActionPerformed

    private void jMenuEdAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdAtendimentoActionPerformed
        new TelaAtendimentoEditar().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdAtendimentoActionPerformed

    private void jMenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioActionPerformed
        new TelaGerenteRelatorio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuRelatorioActionPerformed

    private void jMenuExConsultaAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExConsultaAtendimentoActionPerformed
        new TelaAtendimentoConsulta().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuExConsultaAtendimentoActionPerformed

    private void jMenuConsultaFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaFuncionalActionPerformed
        new Consultar().setVisible(true);
    }//GEN-LAST:event_jMenuConsultaFuncionalActionPerformed

    private void jMenuConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaClienteActionPerformed
        new TelaConsultaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuConsultaClienteActionPerformed

    private void jMenu3SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3SairMouseClicked
        // Botão Sair - tela principal
        System.exit(0);
    }//GEN-LAST:event_jMenu3SairMouseClicked

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField celTextUsu;
    private javax.swing.JTextField complementoTextUsu;
    private javax.swing.JFormattedTextField cpfFormattedUsu;
    private javax.swing.JTextField emailTextUsu;
    private javax.swing.JTextField endTextUsu;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JComboBox<String> expComboBox;
    private javax.swing.JButton jButtonLimpa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCargo1;
    private javax.swing.JLabel jLabelCel;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEnd;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelExpediçao;
    private javax.swing.JLabel jLabelMunicipio;
    private javax.swing.JLabel jLabelNasc;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelOrgao;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3Sair;
    private javax.swing.JMenuItem jMenuAtendimento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuConsultaCliente;
    private javax.swing.JMenuItem jMenuConsultaFuncional;
    private javax.swing.JMenuItem jMenuEdAtendimento;
    private javax.swing.JMenuItem jMenuEdCliente;
    private javax.swing.JMenuItem jMenuEdUsuario;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuExConsultaAtendimento;
    private javax.swing.JMenu jMenuExibir;
    private javax.swing.JMenuItem jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JComboBox<String> municipioComboBox;
    private javax.swing.JFormattedTextField nascFormattedUsu;
    private javax.swing.JTextField nomeTextUsu;
    private javax.swing.JTextField numTextUsu;
    private javax.swing.JComboBox<String> orgaoComboBox;
    private javax.swing.JFormattedTextField rgFormattedUsu;
    private javax.swing.JComboBox<String> selecioneCargo;
    private javax.swing.JPasswordField senhaPasswordCad;
    private javax.swing.JComboBox<String> sexoComboBox;
    private javax.swing.JTextField telTextUsu;
    // End of variables declaration//GEN-END:variables
}
