/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import dao.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author XL
 */

public class TelaEditaUsuario extends javax.swing.JFrame {
private int funcional;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaEditaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        nomeTextGer = new javax.swing.JTextField();
        jLabelTel = new javax.swing.JLabel();
        telTextGer = new javax.swing.JTextField();
        jLabelCel = new javax.swing.JLabel();
        celTextGer = new javax.swing.JTextField();
        jLabelEnd = new javax.swing.JLabel();
        endTextGer = new javax.swing.JTextField();
        jLabelNum = new javax.swing.JLabel();
        numTextGer = new javax.swing.JTextField();
        jLabelComplemento = new javax.swing.JLabel();
        complementoTextGer = new javax.swing.JTextField();
        jLabelMunicipio = new javax.swing.JLabel();
        municipioComboBox = new javax.swing.JComboBox<>();
        jLabelEstado = new javax.swing.JLabel();
        estadoComboBox = new javax.swing.JComboBox<>();
        jLabelCPF = new javax.swing.JLabel();
        cpfFormattedGer = new javax.swing.JFormattedTextField();
        jLabelRG = new javax.swing.JLabel();
        rgFormattedGer = new javax.swing.JFormattedTextField();
        jLabelOrgao = new javax.swing.JLabel();
        orgaoComboBox = new javax.swing.JComboBox<>();
        jLabelExpediçao = new javax.swing.JLabel();
        expComboBox = new javax.swing.JComboBox<>();
        jLabelSexo = new javax.swing.JLabel();
        sexoComboBox = new javax.swing.JComboBox<>();
        jLabelNasc = new javax.swing.JLabel();
        nascFormattedGer = new javax.swing.JFormattedTextField();
        jLabelEmail = new javax.swing.JLabel();
        emailTextGer = new javax.swing.JTextField();
        jLabelCargo = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabelFuncional = new javax.swing.JLabel();
        lupaLabel = new javax.swing.JLabel();
        funcionalTextField = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        senhaTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuAtendimento = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuEdCliente = new javax.swing.JMenuItem();
        jMenuEdUsuario = new javax.swing.JMenuItem();
        jMenuEdAtendimento = new javax.swing.JMenuItem();
        jMenuExibir = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenuItem();
        jMenuExConsultaAtendimento = new javax.swing.JMenuItem();
        jMenuConsultaFuncional = new javax.swing.JMenuItem();
        jMenuConsultaCliente = new javax.swing.JMenuItem();
        jMenu3Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema - Tela Principal");
        getContentPane().setLayout(null);

        jLabelNome.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(51, 102, 0));
        jLabelNome.setText("Nome");
        jLabelNome.setToolTipText("");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(30, 150, 50, 30);

        nomeTextGer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeTextGerMouseClicked(evt);
            }
        });
        nomeTextGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextGerActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextGer);
        nomeTextGer.setBounds(30, 180, 250, 30);

        jLabelTel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelTel.setForeground(new java.awt.Color(51, 102, 0));
        jLabelTel.setText("Tel");
        jLabelTel.setToolTipText("");
        getContentPane().add(jLabelTel);
        jLabelTel.setBounds(290, 150, 50, 30);
        getContentPane().add(telTextGer);
        telTextGer.setBounds(290, 180, 250, 30);

        jLabelCel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelCel.setForeground(new java.awt.Color(51, 102, 0));
        jLabelCel.setText("Cel");
        jLabelCel.setToolTipText("");
        getContentPane().add(jLabelCel);
        jLabelCel.setBounds(560, 150, 50, 30);
        getContentPane().add(celTextGer);
        celTextGer.setBounds(560, 180, 210, 30);

        jLabelEnd.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelEnd.setForeground(new java.awt.Color(51, 102, 0));
        jLabelEnd.setText("Logradouro");
        jLabelEnd.setToolTipText("");
        getContentPane().add(jLabelEnd);
        jLabelEnd.setBounds(30, 220, 90, 40);

        endTextGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTextGerActionPerformed(evt);
            }
        });
        getContentPane().add(endTextGer);
        endTextGer.setBounds(30, 250, 250, 30);

        jLabelNum.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelNum.setForeground(new java.awt.Color(51, 102, 0));
        jLabelNum.setText("Num");
        jLabelNum.setToolTipText("");
        getContentPane().add(jLabelNum);
        jLabelNum.setBounds(300, 220, 40, 40);

        numTextGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTextGerActionPerformed(evt);
            }
        });
        getContentPane().add(numTextGer);
        numTextGer.setBounds(300, 250, 80, 30);

        jLabelComplemento.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelComplemento.setForeground(new java.awt.Color(51, 102, 0));
        jLabelComplemento.setText("Complemento");
        jLabelComplemento.setToolTipText("");
        getContentPane().add(jLabelComplemento);
        jLabelComplemento.setBounds(400, 220, 130, 40);
        getContentPane().add(complementoTextGer);
        complementoTextGer.setBounds(400, 250, 190, 30);

        jLabelMunicipio.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelMunicipio.setForeground(new java.awt.Color(51, 102, 0));
        jLabelMunicipio.setText("Municipio");
        jLabelMunicipio.setToolTipText("");
        getContentPane().add(jLabelMunicipio);
        jLabelMunicipio.setBounds(610, 220, 80, 40);

        municipioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SP", "RS", "MG", "RJ" }));
        municipioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(municipioComboBox);
        municipioComboBox.setBounds(610, 250, 80, 30);

        jLabelEstado.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(51, 102, 0));
        jLabelEstado.setText("Estado");
        jLabelEstado.setToolTipText("");
        getContentPane().add(jLabelEstado);
        jLabelEstado.setBounds(710, 220, 80, 40);

        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "São Paulo", "Rio Grande do Sul", "Minas Gerais", "Rio de Janeiro" }));
        estadoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(estadoComboBox);
        estadoComboBox.setBounds(710, 250, 160, 30);

        jLabelCPF.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(51, 102, 0));
        jLabelCPF.setText("CPF");
        jLabelCPF.setToolTipText("");
        getContentPane().add(jLabelCPF);
        jLabelCPF.setBounds(30, 290, 30, 30);

        try {
            cpfFormattedGer.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(cpfFormattedGer);
        cpfFormattedGer.setBounds(30, 320, 220, 30);

        jLabelRG.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelRG.setForeground(new java.awt.Color(51, 102, 0));
        jLabelRG.setText("RG");
        jLabelRG.setToolTipText("");
        getContentPane().add(jLabelRG);
        jLabelRG.setBounds(260, 290, 30, 20);

        try {
            rgFormattedGer.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(rgFormattedGer);
        rgFormattedGer.setBounds(260, 320, 110, 30);

        jLabelOrgao.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelOrgao.setForeground(new java.awt.Color(51, 102, 0));
        jLabelOrgao.setText("Orgão");
        jLabelOrgao.setToolTipText("");
        getContentPane().add(jLabelOrgao);
        jLabelOrgao.setBounds(380, 290, 50, 20);

        orgaoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SP", "RS", "MG", "RJ" }));
        getContentPane().add(orgaoComboBox);
        orgaoComboBox.setBounds(380, 310, 100, 40);

        jLabelExpediçao.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelExpediçao.setForeground(new java.awt.Color(51, 102, 0));
        jLabelExpediçao.setText("Expedição");
        jLabelExpediçao.setToolTipText("");
        getContentPane().add(jLabelExpediçao);
        jLabelExpediçao.setBounds(490, 280, 90, 40);

        expComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SSP", "PM", "PC", "IFP" }));
        expComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(expComboBox);
        expComboBox.setBounds(490, 310, 90, 40);

        jLabelSexo.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(51, 102, 0));
        jLabelSexo.setText("Sexo");
        jLabelSexo.setToolTipText("");
        getContentPane().add(jLabelSexo);
        jLabelSexo.setBounds(590, 280, 50, 40);

        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));
        sexoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(sexoComboBox);
        sexoComboBox.setBounds(590, 310, 130, 40);

        jLabelNasc.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelNasc.setForeground(new java.awt.Color(51, 102, 0));
        jLabelNasc.setText("Data de nascimento");
        jLabelNasc.setToolTipText("");
        getContentPane().add(jLabelNasc);
        jLabelNasc.setBounds(730, 280, 160, 40);

        try {
            nascFormattedGer.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(nascFormattedGer);
        nascFormattedGer.setBounds(740, 310, 100, 40);

        jLabelEmail.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(51, 102, 0));
        jLabelEmail.setText("Email");
        jLabelEmail.setToolTipText("");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(30, 360, 90, 30);

        emailTextGer.setToolTipText("");
        emailTextGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextGerActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextGer);
        emailTextGer.setBounds(30, 390, 250, 30);

        jLabelCargo.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelCargo.setForeground(new java.awt.Color(51, 102, 0));
        jLabelCargo.setText("Cargo");
        jLabelCargo.setToolTipText("");
        getContentPane().add(jLabelCargo);
        jLabelCargo.setBounds(300, 360, 90, 30);

        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Gerente", "Tecnico", "Atendente" }));
        cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoActionPerformed(evt);
            }
        });
        getContentPane().add(cargo);
        cargo.setBounds(300, 390, 250, 30);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(310, 450, 90, 23);

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(490, 450, 90, 23);

        jLabelFuncional.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelFuncional.setForeground(new java.awt.Color(51, 102, 0));
        jLabelFuncional.setText("Funcional");
        jLabelFuncional.setToolTipText("");
        getContentPane().add(jLabelFuncional);
        jLabelFuncional.setBounds(30, 80, 90, 30);

        lupaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-32.png"))); // NOI18N
        lupaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lupaLabelMousePressed(evt);
            }
        });
        getContentPane().add(lupaLabel);
        lupaLabel.setBounds(140, 110, 40, 30);
        getContentPane().add(funcionalTextField);
        funcionalTextField.setBounds(30, 110, 90, 30);

        jLabelSenha.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(51, 102, 0));
        jLabelSenha.setText("Senha");
        jLabelSenha.setToolTipText("");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(580, 360, 90, 30);
        getContentPane().add(senhaTextField);
        senhaTextField.setBounds(580, 390, 230, 30);

        jLabel1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MASVIG_AttUsuario.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 500);

        jMenuBar4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar4MouseClicked(evt);
            }
        });

        jMenu4.setText("Inicio");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar4.add(jMenu4);

        jMenuSair.setText("Cadastros");

        jMenuCliente.setText("Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuCliente);

        jMenuUsuario.setText("Usuário");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuUsuario);

        jMenuAtendimento.setText("Atendimento");
        jMenuAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAtendimentoActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuAtendimento);

        jMenuBar4.add(jMenuSair);

        jMenuEditar.setText("Editar");

        jMenuEdCliente.setText("Cliente");
        jMenuEdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdClienteActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdCliente);

        jMenuEdUsuario.setText("Usuário");
        jMenuEdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdUsuarioActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdUsuario);

        jMenuEdAtendimento.setText("Atendimento");
        jMenuEdAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdAtendimentoActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdAtendimento);

        jMenuBar4.add(jMenuEditar);

        jMenuExibir.setText("Exibir");

        jMenuRelatorio.setText("Relatórios");
        jMenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuRelatorio);

        jMenuExConsultaAtendimento.setText("Consulta atendimento");
        jMenuExConsultaAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExConsultaAtendimentoActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuExConsultaAtendimento);

        jMenuConsultaFuncional.setText("Consulta funcional");
        jMenuConsultaFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaFuncionalActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaFuncional);

        jMenuConsultaCliente.setText("Consulta cliente");
        jMenuConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaClienteActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaCliente);

        jMenuBar4.add(jMenuExibir);

        jMenu3Sair.setText("Sair");
        jMenu3Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3SairMouseClicked(evt);
            }
        });
        jMenuBar4.add(jMenu3Sair);

        setJMenuBar(jMenuBar4);

        setSize(new java.awt.Dimension(908, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextGerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextGerActionPerformed

    private void emailTextGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextGerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextGerActionPerformed

    private void sexoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoComboBoxActionPerformed

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseClicked
        
        String nome = nomeTextGer.getText();
        String telefone = telTextGer.getText();
        String celular = celTextGer.getText();
        String endereço = endTextGer.getText();
        String numero = numTextGer.getText();
        String complemento = complementoTextGer.getText();
        String estado = estadoComboBox.getSelectedItem().toString();
        String municipio = municipioComboBox.getSelectedItem().toString();
        String cpf = cpfFormattedGer.getText();
        String rg = rgFormattedGer.getText();
        String orgao = orgaoComboBox.getSelectedItem().toString();
        String exp = expComboBox.getSelectedItem().toString();
        String sexo = sexoComboBox.getSelectedItem().toString();
        String nascimento = nascFormattedGer.getText();
        Date data = null;
    	String dataBanco ; 
        try {
            data = (Date) new SimpleDateFormat("dd/MM/yyyy").parse(nascimento);
        } catch (java.text.ParseException e) {
            System.out.println("Ocorreu um erro\n "+e);
        }
        dataBanco = new SimpleDateFormat("yyyy-MM-dd").format(data);
        String email = emailTextGer.getText(); 
        String cargo = this.cargo.getSelectedItem().toString();
        String senha = senhaTextField.getText();
        String num = numTextGer.getText();
        Usuario atualizando = new Usuario(nome, endereço, complemento, municipio, estado, sexo, email, cpf, rg, dataBanco, orgao, exp, cargo, senha, telefone, celular, num);
        atualizando.setFuncional(this.funcional);
        atualizando = atualizando.attUsuario();
        
    }//GEN-LAST:event_jButtonSalvarMouseClicked
    private void nomeTextGerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeTextGerMouseClicked
        //nomeTextUsu.setText("");
    }//GEN-LAST:event_nomeTextGerMouseClicked

    private void endTextGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTextGerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTextGerActionPerformed

    private void numTextGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTextGerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTextGerActionPerformed

    private void municipioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioComboBoxActionPerformed

    private void estadoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoComboBoxActionPerformed

    private void expComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expComboBoxActionPerformed

    private void cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoActionPerformed

    private void lupaLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaLabelMousePressed
        //String funcional = funcionalTextField.getText();
        Usuario funcional = new Usuario(null, null, null, null, null, null, null, null, null, null, null, null, null, null, "0", "0", "0");
        this.funcional = Integer.parseInt(funcionalTextField.getText());
        funcional.setFuncional(Integer.parseInt(funcionalTextField.getText()));
        funcional = funcional.buscaUsuario();
        nomeTextGer.setText(funcional.getNome());
        telTextGer.setText(String.valueOf(funcional.getTelefone()));
        celTextGer.setText(String.valueOf(funcional.getCelular()));
        endTextGer.setText(funcional.getEndereço());
        numTextGer.setText(String.valueOf(funcional.getNum()));
        complementoTextGer.setText(funcional.getComplemento());
        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {funcional.getEstado(),"São Paulo", "Rio Grande do Sul", "Minas Gerais", "Rio de Janeiro"}));
        municipioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {funcional.getMunicipio(),"SELECIONE", "SP", "RS", "MG", "RJ"}));
        cpfFormattedGer.setText(funcional.getCpf());
        rgFormattedGer.setText(funcional.getRg());
        orgaoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {funcional.getOrgao(),"SP", "RS", "MG", "RJ"}));
        expComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {funcional.getExp(),"SSP", "PM", "PC", "IFP"}));
        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {funcional.getSexo(),"Feminino","Masculino"}));
        nascFormattedGer.setText(funcional.getDataNasc());
        emailTextGer.setText(funcional.getEmail()); 
        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {funcional.getCargo(),"Gerente", "Tecnico", "Atendente" }));
        senhaTextField.setText(funcional.getSenha());
        Date data = null;
    	String nascimento = funcional.getDataNasc(); 
        try {
            data = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(nascimento);
        } catch (java.text.ParseException e) {
            System.out.println("Ocorreu um erro\n "+e);
        }
        String dataBanco = new SimpleDateFormat("dd/MM/yyyy").format(data);
        nascFormattedGer.setText(dataBanco);
    }//GEN-LAST:event_lupaLabelMousePressed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        new TelaInicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        new TelaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        new TelaUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAtendimentoActionPerformed
        new TelaAtendimento().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuAtendimentoActionPerformed

    private void jMenuEdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdClienteActionPerformed
        new TelaEditaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdClienteActionPerformed

    private void jMenuEdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdUsuarioActionPerformed
        new TelaEditaUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdUsuarioActionPerformed

    private void jMenuEdAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdAtendimentoActionPerformed
        new TelaAtendimentoEditar().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdAtendimentoActionPerformed

    private void jMenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioActionPerformed
        new TelaGerenteRelatorio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuRelatorioActionPerformed

    private void jMenuExConsultaAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExConsultaAtendimentoActionPerformed
        new TelaAtendimentoConsulta().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuExConsultaAtendimentoActionPerformed

    private void jMenuConsultaFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaFuncionalActionPerformed
        new Consultar().setVisible(true);
    }//GEN-LAST:event_jMenuConsultaFuncionalActionPerformed

    private void jMenuConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaClienteActionPerformed
        new TelaConsultaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuConsultaClienteActionPerformed

    private void jMenu3SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3SairMouseClicked
        // Botão Sair - tela principal
        System.exit(0);
    }//GEN-LAST:event_jMenu3SairMouseClicked

    private void jMenuBar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar4MouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        nomeTextGer.setText("");
        telTextGer.setText("");
        celTextGer.setText("");
        endTextGer.setText("");
        numTextGer.setText("");
        emailTextGer.setText("");
        senhaTextField.setText("");
        complementoTextGer.setText("");
        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "São Paulo", "Rio Grande do Sul", "Minas Gerais", "Rio de Janeiro" }));
        municipioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SP", "RS", "MG", "RJ" }));
        cpfFormattedGer.setText("");
        rgFormattedGer.setText("");
        orgaoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"SELECIONE", "SP", "RS", "MG", "RJ"}));
        expComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE","SSP", "PM", "PC", "IFP"}));
        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"SELECIONE", "Feminino","Masculino"}));
        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"SELECIONE", "Gerente", "Tecnico", "Atendente" }));
        nascFormattedGer.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cargo;
    private javax.swing.JTextField celTextGer;
    private javax.swing.JTextField complementoTextGer;
    private javax.swing.JFormattedTextField cpfFormattedGer;
    private javax.swing.JTextField emailTextGer;
    private javax.swing.JTextField endTextGer;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JComboBox<String> expComboBox;
    private javax.swing.JTextField funcionalTextField;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCel;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEnd;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelExpediçao;
    private javax.swing.JLabel jLabelFuncional;
    private javax.swing.JLabel jLabelMunicipio;
    private javax.swing.JLabel jLabelNasc;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelOrgao;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JMenu jMenu3Sair;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuAtendimento;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuConsultaCliente;
    private javax.swing.JMenuItem jMenuConsultaFuncional;
    private javax.swing.JMenuItem jMenuEdAtendimento;
    private javax.swing.JMenuItem jMenuEdCliente;
    private javax.swing.JMenuItem jMenuEdUsuario;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuExConsultaAtendimento;
    private javax.swing.JMenu jMenuExibir;
    private javax.swing.JMenuItem jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JLabel lupaLabel;
    private javax.swing.JComboBox<String> municipioComboBox;
    private javax.swing.JFormattedTextField nascFormattedGer;
    private javax.swing.JTextField nomeTextGer;
    private javax.swing.JTextField numTextGer;
    private javax.swing.JComboBox<String> orgaoComboBox;
    private javax.swing.JFormattedTextField rgFormattedGer;
    private javax.swing.JTextField senhaTextField;
    private javax.swing.JComboBox<String> sexoComboBox;
    private javax.swing.JTextField telTextGer;
    // End of variables declaration//GEN-END:variables
}
