/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.Atendimento;
import dao.AtendimentoDAO;
import dao.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author XL
 */
public class TelaAtendimento extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtendimento
     */
    public TelaAtendimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idAtendimento = new javax.swing.JLabel();
        idAtendimentoTextField = new javax.swing.JTextField();
        tipoComboBox = new javax.swing.JComboBox<>();
        clienteLabelAtend = new javax.swing.JLabel();
        clienteTextFieldAtend = new javax.swing.JTextField();
        lupaLabelAtend = new javax.swing.JLabel();
        userLabelAtend = new javax.swing.JLabel();
        funcionalTextFieldAtend = new javax.swing.JTextField();
        telLabelAtend = new javax.swing.JLabel();
        telTextFieldAtend = new javax.swing.JTextField();
        emailLabelAtend = new javax.swing.JLabel();
        emailTextFieldAtend = new javax.swing.JTextField();
        respLabelAtend = new javax.swing.JLabel();
        respTextFieldAtend = new javax.swing.JTextField();
        grauLabelAtend = new javax.swing.JLabel();
        assuntoLabelAtend = new javax.swing.JLabel();
        assuntoTextFieldAtend = new javax.swing.JTextField();
        descriTextFieldAtend = new javax.swing.JTextField();
        saveButtonAtend = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuChamado = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuEdCliente = new javax.swing.JMenuItem();
        jMenuEdUsuario = new javax.swing.JMenuItem();
        jMenuEdChamado = new javax.swing.JMenuItem();
        jMenuExibir = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenuItem();
        jMenuExConsulta = new javax.swing.JMenuItem();
        jMenuConsultaFuncional = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(null);

        idAtendimento.setText("id_atendimento");
        getContentPane().add(idAtendimento);
        idAtendimento.setBounds(10, 10, 90, 20);

        idAtendimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAtendimentoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(idAtendimentoTextField);
        idAtendimentoTextField.setBounds(10, 30, 120, 30);

        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Razão Social", "CNPJ" }));
        tipoComboBox.setToolTipText("Selecione");
        getContentPane().add(tipoComboBox);
        tipoComboBox.setBounds(150, 30, 90, 30);

        clienteLabelAtend.setText("Cliente");
        getContentPane().add(clienteLabelAtend);
        clienteLabelAtend.setBounds(250, 10, 120, 24);

        clienteTextFieldAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTextFieldAtendActionPerformed(evt);
            }
        });
        getContentPane().add(clienteTextFieldAtend);
        clienteTextFieldAtend.setBounds(250, 30, 180, 30);

        lupaLabelAtend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-32.png"))); // NOI18N
        lupaLabelAtend.setText("jLabel5");
        lupaLabelAtend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaLabelAtendMouseClicked(evt);
            }
        });
        getContentPane().add(lupaLabelAtend);
        lupaLabelAtend.setBounds(440, 30, 30, 30);

        userLabelAtend.setText("Usuário");
        getContentPane().add(userLabelAtend);
        userLabelAtend.setBounds(530, 10, 70, 20);

        funcionalTextFieldAtend.setText("Quem é o user");
        funcionalTextFieldAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionalTextFieldAtendActionPerformed(evt);
            }
        });
        getContentPane().add(funcionalTextFieldAtend);
        funcionalTextFieldAtend.setBounds(530, 30, 190, 30);

        telLabelAtend.setText("Telefone");
        getContentPane().add(telLabelAtend);
        telLabelAtend.setBounds(20, 140, 80, 14);

        telTextFieldAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTextFieldAtendActionPerformed(evt);
            }
        });
        getContentPane().add(telTextFieldAtend);
        telTextFieldAtend.setBounds(20, 160, 130, 30);

        emailLabelAtend.setText("Email");
        getContentPane().add(emailLabelAtend);
        emailLabelAtend.setBounds(170, 140, 24, 14);
        getContentPane().add(emailTextFieldAtend);
        emailTextFieldAtend.setBounds(170, 160, 180, 30);

        respLabelAtend.setText("Responsável");
        getContentPane().add(respLabelAtend);
        respLabelAtend.setBounds(370, 140, 80, 14);

        respTextFieldAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respTextFieldAtendActionPerformed(evt);
            }
        });
        getContentPane().add(respTextFieldAtend);
        respTextFieldAtend.setBounds(370, 160, 130, 30);

        grauLabelAtend.setText("Grau de urgência");
        getContentPane().add(grauLabelAtend);
        grauLabelAtend.setBounds(530, 80, 110, 20);

        assuntoLabelAtend.setText("Assunto");
        getContentPane().add(assuntoLabelAtend);
        assuntoLabelAtend.setBounds(30, 210, 70, 20);

        assuntoTextFieldAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assuntoTextFieldAtendActionPerformed(evt);
            }
        });
        getContentPane().add(assuntoTextFieldAtend);
        assuntoTextFieldAtend.setBounds(30, 230, 410, 30);

        descriTextFieldAtend.setText("Descrição");
        descriTextFieldAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriTextFieldAtendActionPerformed(evt);
            }
        });
        getContentPane().add(descriTextFieldAtend);
        descriTextFieldAtend.setBounds(30, 270, 410, 160);

        saveButtonAtend.setText("Salvar");
        saveButtonAtend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonAtendMouseClicked(evt);
            }
        });
        getContentPane().add(saveButtonAtend);
        saveButtonAtend.setBounds(480, 390, 90, 23);

        jButton2.setText("Limpar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 390, 80, 23);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 100, 210, 30);

        jLabel1.setText("Empresa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 74, 140, 20);

        jLabel2.setText("CNPJ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 80, 25, 14);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(250, 100, 190, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Alta", "Atipica", "Baixa", "Media" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(530, 100, 160, 30);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
        });

        jMenuInicio.setText("Inicio");
        jMenuBar1.add(jMenuInicio);

        jMenuSair.setText("Cadastros");

        jMenuCliente.setText("Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuCliente);

        jMenuUsuario.setText("Usuário");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuUsuario);

        jMenuChamado.setText("Chamado");
        jMenuChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuChamadoActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuChamado);

        jMenuBar1.add(jMenuSair);

        jMenuEditar.setText("Editar");

        jMenuEdCliente.setText("Cliente");
        jMenuEdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdClienteActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdCliente);

        jMenuEdUsuario.setText("Usuário");
        jMenuEdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdUsuarioActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdUsuario);

        jMenuEdChamado.setText("Chamado");
        jMenuEdChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdChamadoActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdChamado);

        jMenuBar1.add(jMenuEditar);

        jMenuExibir.setText("Exibir");

        jMenuRelatorio.setText("Relatórios");
        jMenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuRelatorio);

        jMenuExConsulta.setText("Consulta atendimento");
        jMenuExConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExConsultaActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuExConsulta);

        jMenuConsultaFuncional.setText("Consulta funcional");
        jMenuConsultaFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaFuncionalActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaFuncional);

        jMenuItem1.setText("Consulta cliente");
        jMenuExibir.add(jMenuItem1);

        jMenuBar1.add(jMenuExibir);

        jMenu3Sair.setText("Sair");
        jMenu3Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3SairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3Sair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(807, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void funcionalTextFieldAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionalTextFieldAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcionalTextFieldAtendActionPerformed

    private void clienteTextFieldAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTextFieldAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTextFieldAtendActionPerformed

    private void descriTextFieldAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriTextFieldAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriTextFieldAtendActionPerformed

    private void idAtendimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAtendimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAtendimentoTextFieldActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        new TelaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        new TelaUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuChamadoActionPerformed
        new TelaAtendimento().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuChamadoActionPerformed

    private void jMenuEdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdClienteActionPerformed
        new TelaEditaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdClienteActionPerformed

    private void jMenuEdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdUsuarioActionPerformed
        new TelaEditaUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdUsuarioActionPerformed

    private void jMenuEdChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdChamadoActionPerformed
        new TelaAtendimentoEditar().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdChamadoActionPerformed

    private void jMenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioActionPerformed
        new TelaGerenteRelatorio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuRelatorioActionPerformed

    private void jMenuExConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExConsultaActionPerformed
        new TelaAtendimentoConsulta().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuExConsultaActionPerformed

    private void jMenuConsultaFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaFuncionalActionPerformed
        new Consultar().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuConsultaFuncionalActionPerformed

    private void jMenu3SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3SairMouseClicked
        // Botão Sair - tela principal
        System.exit(0);
    }//GEN-LAST:event_jMenu3SairMouseClicked

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void saveButtonAtendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonAtendMouseClicked
        String assunto = assuntoTextFieldAtend.getText();
        String descriçao = descriTextFieldAtend.getText();
        String email = emailTextFieldAtend.getText();
        String responsavel = respTextFieldAtend.getText();
        String telefone = telTextFieldAtend.getText();
        
        Atendimento novo = new Atendimento(assunto, descriçao, email, responsavel, telefone);
        
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
        assuntoTextFieldAtend.setText("");
        descriTextFieldAtend.setText("");
        emailTextFieldAtend.setText("");
        respTextFieldAtend.setText("");
        telTextFieldAtend.setText("");
    }//GEN-LAST:event_saveButtonAtendMouseClicked

    private void assuntoTextFieldAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assuntoTextFieldAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assuntoTextFieldAtendActionPerformed

    private void telTextFieldAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTextFieldAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telTextFieldAtendActionPerformed

    private void respTextFieldAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respTextFieldAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respTextFieldAtendActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        assuntoTextFieldAtend.setText("");
        descriTextFieldAtend.setText("");
        emailTextFieldAtend.setText("");
        respTextFieldAtend.setText("");
        telTextFieldAtend.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void lupaLabelAtendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaLabelAtendMouseClicked
       if(tipoComboBox.getSelectedItem().equals("Razão Social")){
        String busca = clienteTextFieldAtend.getText();
        AtendimentoDAO atend = new AtendimentoDAO();
        //atend.consultaRazao(busca);
       }
        
        
    }//GEN-LAST:event_lupaLabelAtendMouseClicked

      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assuntoLabelAtend;
    private javax.swing.JTextField assuntoTextFieldAtend;
    private javax.swing.JLabel clienteLabelAtend;
    private javax.swing.JTextField clienteTextFieldAtend;
    private javax.swing.JTextField descriTextFieldAtend;
    private javax.swing.JLabel emailLabelAtend;
    private javax.swing.JTextField emailTextFieldAtend;
    private javax.swing.JTextField funcionalTextFieldAtend;
    private javax.swing.JLabel grauLabelAtend;
    private javax.swing.JLabel idAtendimento;
    private javax.swing.JTextField idAtendimentoTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3Sair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuChamado;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuConsultaFuncional;
    private javax.swing.JMenuItem jMenuEdChamado;
    private javax.swing.JMenuItem jMenuEdCliente;
    private javax.swing.JMenuItem jMenuEdUsuario;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuExConsulta;
    private javax.swing.JMenu jMenuExibir;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lupaLabelAtend;
    private javax.swing.JLabel respLabelAtend;
    private javax.swing.JTextField respTextFieldAtend;
    private javax.swing.JButton saveButtonAtend;
    private javax.swing.JLabel telLabelAtend;
    private javax.swing.JTextField telTextFieldAtend;
    private javax.swing.JComboBox<String> tipoComboBox;
    private javax.swing.JLabel userLabelAtend;
    // End of variables declaration//GEN-END:variables
}
