/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import dao.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author XL
 */
public class TelaEditaCliente extends javax.swing.JFrame {

    private String cnpj;                                             
    private Cliente buscaCliente;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaEditaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        nomeTextCad = new javax.swing.JTextField();
        jLabelTel = new javax.swing.JLabel();
        telTextCad = new javax.swing.JTextField();
        jLabelCel = new javax.swing.JLabel();
        celTextCad = new javax.swing.JTextField();
        jLabelEnd = new javax.swing.JLabel();
        endTextCad = new javax.swing.JTextField();
        jLabelNum = new javax.swing.JLabel();
        numTextCad = new javax.swing.JTextField();
        jLabelComplemento = new javax.swing.JLabel();
        complementoTextCad = new javax.swing.JTextField();
        jLabelMunicipio = new javax.swing.JLabel();
        municipioComboBox = new javax.swing.JComboBox<>();
        jLabelEstado = new javax.swing.JLabel();
        estadoComboBox = new javax.swing.JComboBox<>();
        jLabelCNPJ = new javax.swing.JLabel();
        cnpjFormattedCad = new javax.swing.JFormattedTextField();
        jLabelRazao = new javax.swing.JLabel();
        razaoTextField = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        emailTextCad = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        buscarLabel = new javax.swing.JLabel();
        buscacnpjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabelBuscaCnpj = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuAtendimento = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuEdCliente = new javax.swing.JMenuItem();
        jMenuEdUsuario = new javax.swing.JMenuItem();
        jMenuEdAtendimento = new javax.swing.JMenuItem();
        jMenuExibir = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenuItem();
        jMenuExConsultaAtendimento = new javax.swing.JMenuItem();
        jMenuConsultaFuncional = new javax.swing.JMenuItem();
        jMenuConsultaCliente = new javax.swing.JMenuItem();
        jMenu3Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TelaCliente");
        getContentPane().setLayout(null);

        jLabelNome.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(51, 102, 0));
        jLabelNome.setText("Nome");
        jLabelNome.setToolTipText("");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(40, 150, 50, 30);

        nomeTextCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeTextCadMouseClicked(evt);
            }
        });
        nomeTextCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextCadActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextCad);
        nomeTextCad.setBounds(40, 180, 250, 30);

        jLabelTel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelTel.setForeground(new java.awt.Color(51, 102, 0));
        jLabelTel.setText("Tel");
        jLabelTel.setToolTipText("");
        getContentPane().add(jLabelTel);
        jLabelTel.setBounds(310, 290, 50, 30);
        getContentPane().add(telTextCad);
        telTextCad.setBounds(310, 320, 240, 30);

        jLabelCel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelCel.setForeground(new java.awt.Color(51, 102, 0));
        jLabelCel.setText("Cel");
        jLabelCel.setToolTipText("");
        getContentPane().add(jLabelCel);
        jLabelCel.setBounds(570, 290, 50, 30);
        getContentPane().add(celTextCad);
        celTextCad.setBounds(570, 320, 210, 30);

        jLabelEnd.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelEnd.setForeground(new java.awt.Color(51, 102, 0));
        jLabelEnd.setText("Logradouro");
        jLabelEnd.setToolTipText("");
        getContentPane().add(jLabelEnd);
        jLabelEnd.setBounds(40, 220, 90, 40);

        endTextCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTextCadActionPerformed(evt);
            }
        });
        getContentPane().add(endTextCad);
        endTextCad.setBounds(40, 250, 250, 30);

        jLabelNum.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelNum.setForeground(new java.awt.Color(51, 102, 0));
        jLabelNum.setText("Num");
        jLabelNum.setToolTipText("");
        getContentPane().add(jLabelNum);
        jLabelNum.setBounds(310, 220, 40, 40);

        numTextCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTextCadActionPerformed(evt);
            }
        });
        getContentPane().add(numTextCad);
        numTextCad.setBounds(310, 250, 80, 30);

        jLabelComplemento.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelComplemento.setForeground(new java.awt.Color(51, 102, 0));
        jLabelComplemento.setText("Complemento");
        jLabelComplemento.setToolTipText("");
        getContentPane().add(jLabelComplemento);
        jLabelComplemento.setBounds(410, 220, 130, 40);
        getContentPane().add(complementoTextCad);
        complementoTextCad.setBounds(410, 250, 190, 30);

        jLabelMunicipio.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelMunicipio.setForeground(new java.awt.Color(51, 102, 0));
        jLabelMunicipio.setText("Municipio");
        jLabelMunicipio.setToolTipText("");
        getContentPane().add(jLabelMunicipio);
        jLabelMunicipio.setBounds(620, 220, 80, 40);

        municipioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SP", "RS", "MG", "RJ" }));
        municipioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(municipioComboBox);
        municipioComboBox.setBounds(620, 250, 80, 30);

        jLabelEstado.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(51, 102, 0));
        jLabelEstado.setText("Estado");
        jLabelEstado.setToolTipText("");
        getContentPane().add(jLabelEstado);
        jLabelEstado.setBounds(720, 220, 80, 40);

        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "São Paulo", "Rio Grande do Sul", "Minas Gerais", "Rio de Janeiro" }));
        estadoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(estadoComboBox);
        estadoComboBox.setBounds(720, 250, 160, 30);

        jLabelCNPJ.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelCNPJ.setForeground(new java.awt.Color(51, 102, 0));
        jLabelCNPJ.setText("CNPJ");
        jLabelCNPJ.setToolTipText("");
        getContentPane().add(jLabelCNPJ);
        jLabelCNPJ.setBounds(310, 150, 50, 30);

        try {
            cnpjFormattedCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpjFormattedCad.setToolTipText("oiii");
        cnpjFormattedCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjFormattedCadActionPerformed(evt);
            }
        });
        getContentPane().add(cnpjFormattedCad);
        cnpjFormattedCad.setBounds(310, 180, 250, 30);

        jLabelRazao.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelRazao.setForeground(new java.awt.Color(51, 102, 0));
        jLabelRazao.setText("Razão social");
        jLabelRazao.setToolTipText("");
        getContentPane().add(jLabelRazao);
        jLabelRazao.setBounds(580, 150, 150, 30);
        getContentPane().add(razaoTextField);
        razaoTextField.setBounds(580, 180, 290, 30);

        jLabelEmail.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(51, 102, 0));
        jLabelEmail.setText("Email");
        jLabelEmail.setToolTipText("");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(40, 290, 90, 30);

        emailTextCad.setToolTipText("");
        emailTextCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextCadActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextCad);
        emailTextCad.setBounds(40, 320, 250, 30);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(320, 400, 80, 23);

        jButtonCancel.setText("Limpar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(430, 400, 90, 23);

        buscarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-32.png"))); // NOI18N
        buscarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarLabelMousePressed(evt);
            }
        });
        getContentPane().add(buscarLabel);
        buscarLabel.setBounds(270, 100, 30, 40);

        try {
            buscacnpjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(buscacnpjFormattedTextField);
        buscacnpjFormattedTextField.setBounds(40, 110, 220, 30);

        jLabelBuscaCnpj.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelBuscaCnpj.setForeground(new java.awt.Color(51, 102, 0));
        jLabelBuscaCnpj.setText("Busca CNPJ");
        jLabelBuscaCnpj.setToolTipText("");
        getContentPane().add(jLabelBuscaCnpj);
        jLabelBuscaCnpj.setBounds(40, 80, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MASVIG_AttCliente.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 890, 480);

        jMenuBar4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar4MouseClicked(evt);
            }
        });

        jMenu4.setText("Inicio");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar4.add(jMenu4);

        jMenuSair.setText("Cadastros");

        jMenuCliente.setText("Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuCliente);

        jMenuUsuario.setText("Usuário");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuUsuario);

        jMenuAtendimento.setText("Atendimento");
        jMenuAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAtendimentoActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuAtendimento);

        jMenuBar4.add(jMenuSair);

        jMenuEditar.setText("Editar");

        jMenuEdCliente.setText("Cliente");
        jMenuEdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdClienteActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdCliente);

        jMenuEdUsuario.setText("Usuário");
        jMenuEdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdUsuarioActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdUsuario);

        jMenuEdAtendimento.setText("Atendimento");
        jMenuEdAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdAtendimentoActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdAtendimento);

        jMenuBar4.add(jMenuEditar);

        jMenuExibir.setText("Exibir");

        jMenuRelatorio.setText("Relatórios");
        jMenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuRelatorio);

        jMenuExConsultaAtendimento.setText("Consulta atendimento");
        jMenuExConsultaAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExConsultaAtendimentoActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuExConsultaAtendimento);

        jMenuConsultaFuncional.setText("Consulta funcional");
        jMenuConsultaFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaFuncionalActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaFuncional);

        jMenuConsultaCliente.setText("Consulta cliente");
        jMenuConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaClienteActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaCliente);

        jMenuBar4.add(jMenuExibir);

        jMenu3Sair.setText("Sair");
        jMenu3Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3SairMouseClicked(evt);
            }
        });
        jMenuBar4.add(jMenu3Sair);

        setJMenuBar(jMenuBar4);

        setSize(new java.awt.Dimension(906, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextCadActionPerformed

    private void emailTextCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextCadActionPerformed

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseClicked

    }//GEN-LAST:event_jButtonSalvarMouseClicked

    private void nomeTextCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeTextCadMouseClicked
        //nomeTextUsu.setText("");
    }//GEN-LAST:event_nomeTextCadMouseClicked

    private void endTextCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTextCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTextCadActionPerformed

    private void numTextCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTextCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTextCadActionPerformed

    private void municipioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioComboBoxActionPerformed

    private void estadoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoComboBoxActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       int erro = 0;
        
        String nome = nomeTextCad.getText();
        String cnpj = cnpjFormattedCad.getText();
        String razao = razaoTextField.getText();
        String logradouro = endTextCad.getText();
        String num = numTextCad.getText(); 
        String complemento = complementoTextCad.getText();
        String estado = estadoComboBox.getEditor().getItem().toString();
        String municipio = municipioComboBox.getEditor().getItem().toString();
        String email = emailTextCad.getText();
        String telefone = telTextCad.getText();
        String celular = celTextCad.getText();
        
        this.cnpj = cnpj;
        try{
            int telefoneInteger = Integer.parseInt(telefone);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ERRO, o telefone possui letras!");
            erro++;
        }   
        if(telefone.length() > 8){
            JOptionPane.showMessageDialog(null, "ERRO, o telefone excede o limite de caracteres");
            erro++;
        }
        
        
        
        if(erro == 0){
            Cliente atualizar = new Cliente(cnpj, razao, nome, logradouro, estado, complemento, municipio, email, num, telefone, celular);
            atualizar.setCnpjEditar(buscacnpjFormattedTextField.getText());
            atualizar.setCnpj(this.cnpj);
            if(atualizar.attCliente()== true){
            JOptionPane.showMessageDialog(null, "Sucesso ao atualizar o cliente");
            cnpjFormattedCad.setText(atualizar.getCnpj());
            buscacnpjFormattedTextField.setText("");
            nomeTextCad.setText("");
            cnpjFormattedCad.setText("");
            razaoTextField.setText("");
            endTextCad.setText("");
            numTextCad.setText(""); 
            complementoTextCad.setText("");
            estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "São Paulo", "Rio Grande do Sul", "Minas Gerais", "Rio de Janeiro" }));
            municipioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SP", "RS", "MG", "RJ" }));
            emailTextCad.setText("");
            telTextCad.setText("");
            celTextCad.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar atualizar o cliente");
                cnpjFormattedCad.setText("ERRO!");
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void buscarLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarLabelMousePressed
       if(buscacnpjFormattedTextField.getText().length() > 0){
            String cnpj = buscacnpjFormattedTextField.getText();
            int erro = 0;
            try{
                this.cnpj = cnpj;
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "ERRO, o cnpj possui letras!");
                erro++;
            }
            if(erro == 0){
                Cliente buscar = new Cliente(null, null, null, null, null, null, null, null, "0", "0", "0");
                this.buscaCliente = buscar.getCliente(this.cnpj);
                if(this.buscaCliente == null){
                    JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
                } else {
                    String telefone = String.valueOf(this.buscaCliente.getTelefone());
                    String celular = String.valueOf(this.buscaCliente.getCelular());
                    String num = String.valueOf(this.buscaCliente.getNum());
                    nomeTextCad.setText(this.buscaCliente.getNome());
                    cnpjFormattedCad.setText(this.buscaCliente.getCnpj());
                    razaoTextField.setText(this.buscaCliente.getRazaoSocial());
                    complementoTextCad.setText(this.buscaCliente.getComplemento());
                    municipioComboBox.getEditor().setItem(this.buscaCliente.getMunicipio());
                    endTextCad.setText(this.buscaCliente.getEndereço());
                    estadoComboBox.getEditor().setItem(this.buscaCliente.getEstado());
                    emailTextCad.setText(this.buscaCliente.getEmail());
                    telTextCad.setText(telefone);
                    celTextCad.setText(celular);
                    numTextCad.setText(num);
                    //this.cnpj = this.buscaCliente.getBuscaCnpj();
                }
            }
        }                  /**/                       
    }//GEN-LAST:event_buscarLabelMousePressed

    private void cnpjFormattedCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjFormattedCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjFormattedCadActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        new TelaInicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        new TelaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        new TelaUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAtendimentoActionPerformed
        new TelaAtendimento().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuAtendimentoActionPerformed

    private void jMenuEdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdClienteActionPerformed
        new TelaEditaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdClienteActionPerformed

    private void jMenuEdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdUsuarioActionPerformed
        new TelaEditaUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdUsuarioActionPerformed

    private void jMenuEdAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdAtendimentoActionPerformed
        new TelaAtendimentoEditar().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdAtendimentoActionPerformed

    private void jMenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioActionPerformed
        new TelaGerenteRelatorio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuRelatorioActionPerformed

    private void jMenuExConsultaAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExConsultaAtendimentoActionPerformed
        new TelaAtendimentoConsulta().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuExConsultaAtendimentoActionPerformed

    private void jMenuConsultaFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaFuncionalActionPerformed
        new Consultar().setVisible(true);
    }//GEN-LAST:event_jMenuConsultaFuncionalActionPerformed

    private void jMenuConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaClienteActionPerformed
        new TelaConsultaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuConsultaClienteActionPerformed

    private void jMenu3SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3SairMouseClicked
        // Botão Sair - tela principal
        System.exit(0);
    }//GEN-LAST:event_jMenu3SairMouseClicked

    private void jMenuBar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar4MouseClicked

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        buscacnpjFormattedTextField.setText("");
            nomeTextCad.setText("");
            cnpjFormattedCad.setText("");
            razaoTextField.setText("");
            endTextCad.setText("");
            numTextCad.setText(""); 
            complementoTextCad.setText("");
            estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "São Paulo", "Rio Grande do Sul", "Minas Gerais", "Rio de Janeiro" }));
            municipioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SP", "RS", "MG", "RJ" }));
            emailTextCad.setText("");
            telTextCad.setText("");
            celTextCad.setText("");
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField buscacnpjFormattedTextField;
    private javax.swing.JLabel buscarLabel;
    private javax.swing.JTextField celTextCad;
    private javax.swing.JFormattedTextField cnpjFormattedCad;
    private javax.swing.JTextField complementoTextCad;
    private javax.swing.JTextField emailTextCad;
    private javax.swing.JTextField endTextCad;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBuscaCnpj;
    private javax.swing.JLabel jLabelCNPJ;
    private javax.swing.JLabel jLabelCel;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEnd;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelMunicipio;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelRazao;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JMenu jMenu3Sair;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuAtendimento;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuConsultaCliente;
    private javax.swing.JMenuItem jMenuConsultaFuncional;
    private javax.swing.JMenuItem jMenuEdAtendimento;
    private javax.swing.JMenuItem jMenuEdCliente;
    private javax.swing.JMenuItem jMenuEdUsuario;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuExConsultaAtendimento;
    private javax.swing.JMenu jMenuExibir;
    private javax.swing.JMenuItem jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JComboBox<String> municipioComboBox;
    private javax.swing.JTextField nomeTextCad;
    private javax.swing.JTextField numTextCad;
    private javax.swing.JTextField razaoTextField;
    private javax.swing.JTextField telTextCad;
    // End of variables declaration//GEN-END:variables
}
