/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.Auth;
import dao.ConexaoDAO;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author XL
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Acessar = new javax.swing.JButton();
        jButton2Sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1Usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField2Senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Login");
        setResizable(false);
        setSize(new java.awt.Dimension(920, 490));
        getContentPane().setLayout(null);

        jButton1Acessar.setText("Acessar");
        jButton1Acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AcessarActionPerformed(evt);
            }
        });
        jButton1Acessar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1AcessarKeyPressed(evt);
            }
        });
        getContentPane().add(jButton1Acessar);
        jButton1Acessar.setBounds(320, 340, 80, 23);

        jButton2Sair.setText("Sair");
        jButton2Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2SairActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Sair);
        jButton2Sair.setBounds(450, 340, 80, 23);

        jLabel2.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("Usuário.:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 190, 72, 30);
        getContentPane().add(jTextField1Usuario);
        jTextField1Usuario.setBounds(400, 190, 140, 30);

        jLabel3.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 0));
        jLabel3.setText("Senha.:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 250, 80, 24);

        jPasswordField2Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2Senha);
        jPasswordField2Senha.setBounds(400, 240, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MASVIG_phixr.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(920, 490));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 490);

        setSize(new java.awt.Dimension(903, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1AcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AcessarActionPerformed
        
        Auth auth = new Auth(Integer.parseInt(jTextField1Usuario.getText()), jPasswordField2Senha.getText());
        //System.out.println(auth.authSucesso());
        
        if(auth.authSucesso()){
        TelaInicio tela = new TelaInicio();
        tela.setVisible(true); // verifica se o objeto tela existe
        dispose();   // serve pra fechar a tela de login apos a sua autenticação     
        }
        else {
            JOptionPane.showMessageDialog(null, "Usuário ou senha incorreto!");
        }
    }//GEN-LAST:event_jButton1AcessarActionPerformed

    private void jButton2SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SairActionPerformed
        // Botão de Saída - Tela login
         System.exit(0);
    }//GEN-LAST:event_jButton2SairActionPerformed

    private void jButton1AcessarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1AcessarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1AcessarKeyPressed

    private void jPasswordField2SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2SenhaActionPerformed

    }//GEN-LAST:event_jPasswordField2SenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Thread(){
                    @Override
                    public void run() {
                        try 
                        { 
                            ConexaoDAO DAO =  new ConexaoDAO();
                            Connection conn = DAO.getConexao();
                        } catch (Exception ex){}
                        
                    }
                    
                }.start();
                
                new Thread(){
                    @Override
                    public void run() {
                        try 
                        { 
                            new TelaLogin().setVisible(true);
                        } catch (Exception ex){}
                        
                    }
                    
                }.start();

                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Acessar;
    private javax.swing.JButton jButton2Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField2Senha;
    private javax.swing.JTextField jTextField1Usuario;
    // End of variables declaration//GEN-END:variables
}
