/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import dao.*;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author XL
 */
public class TelaAtendimentoConsulta extends javax.swing.JFrame {
    
    private int id_atendimento;                                             
    private Atendimento buscaAtendimento;
    private String cnpj;
    
    
    /**
     * Creates new form TelaAtendimento
     */
    public TelaAtendimentoConsulta() {
        initComponents();
        listarTodosOsAtendimentos();
    }
    
    public void listarTodosOsAtendimentos(){
        Atendimento listados = new Atendimento(null, null, null, null, "0", null);
        this.cnpj = clienteTextFieldGerCon.getText();
        listados.todosOsClientes(0, null);
        
        int tamanho = listados.listaId.size();
        
        javax.swing.table.DefaultTableModel dtm2 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        dtm2.setNumRows(0);
        //ISSO TIRA AS LINHAS DA TABELA
        int x=0;
        
        for(int i = 0; i < tamanho; i++){
            dtm2.addRow(new Object[]{" "," "," "," "," "," "});// cada " " para cada coluna
            jTable1.setValueAt(String.valueOf(listados.listaId.get(i)),x,0);
            jTable1.setValueAt(listados.listaNome.get(i),x,1);
            jTable1.setValueAt(String.valueOf(listados.listaTelefone.get(i)),x,2);
            jTable1.setValueAt(listados.listaEmail.get(i),x,3);
            jTable1.setValueAt(listados.listaResponsavel.get(i),x,4);
            jTable1.setValueAt(listados.listaAssunto.get(i),x,5);
            x++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idAtendimento = new javax.swing.JLabel();
        idAtendimentoTextField = new javax.swing.JTextField();
        clienteLabelGerCon = new javax.swing.JLabel();
        clienteTextFieldGerCon = new javax.swing.JTextField();
        lupaLabelGerCon = new javax.swing.JLabel();
        userLabelGerCon = new javax.swing.JLabel();
        funcionalTextFieldGerCon = new javax.swing.JTextField();
        telLabelGerCon = new javax.swing.JLabel();
        telTextFieldGerCon = new javax.swing.JTextField();
        emailLabelGerCon = new javax.swing.JLabel();
        emailTextFieldGerCon = new javax.swing.JTextField();
        respLabelGerCon = new javax.swing.JLabel();
        respTextFieldGerCon = new javax.swing.JTextField();
        assuntoLabelGerCon = new javax.swing.JLabel();
        assuntoTextFieldGerCon = new javax.swing.JTextField();
        lupaLabelGerCon1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriTextFieldGerCon = new javax.swing.JTextArea();
        assuntoLabelGerCon1 = new javax.swing.JLabel();
        ultimosAtendimentos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuAtendimento = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuEdCliente = new javax.swing.JMenuItem();
        jMenuEdUsuario = new javax.swing.JMenuItem();
        jMenuEdAtendimento = new javax.swing.JMenuItem();
        jMenuExibir = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenuItem();
        jMenuExConsultaAtendimento = new javax.swing.JMenuItem();
        jMenuConsultaFuncional = new javax.swing.JMenuItem();
        jMenuConsultaCliente = new javax.swing.JMenuItem();
        jMenu3Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chamados");
        setSize(new java.awt.Dimension(1800, 800));
        getContentPane().setLayout(null);

        idAtendimento.setText("Id do atendimento");
        getContentPane().add(idAtendimento);
        idAtendimento.setBounds(40, 20, 90, 20);

        idAtendimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAtendimentoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(idAtendimentoTextField);
        idAtendimentoTextField.setBounds(40, 40, 120, 30);

        clienteLabelGerCon.setText("CNPJ Cliente");
        getContentPane().add(clienteLabelGerCon);
        clienteLabelGerCon.setBounds(210, 20, 90, 24);

        clienteTextFieldGerCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTextFieldGerConActionPerformed(evt);
            }
        });
        getContentPane().add(clienteTextFieldGerCon);
        clienteTextFieldGerCon.setBounds(210, 40, 200, 30);

        lupaLabelGerCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-32.png"))); // NOI18N
        lupaLabelGerCon.setText("jLabel5");
        lupaLabelGerCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaLabelGerConMouseClicked(evt);
            }
        });
        getContentPane().add(lupaLabelGerCon);
        lupaLabelGerCon.setBounds(160, 40, 30, 30);

        userLabelGerCon.setText("Usuário");
        getContentPane().add(userLabelGerCon);
        userLabelGerCon.setBounds(450, 20, 70, 20);

        funcionalTextFieldGerCon.setEditable(false);
        funcionalTextFieldGerCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionalTextFieldGerConActionPerformed(evt);
            }
        });
        getContentPane().add(funcionalTextFieldGerCon);
        funcionalTextFieldGerCon.setBounds(450, 40, 150, 30);

        telLabelGerCon.setText("Telefone");
        getContentPane().add(telLabelGerCon);
        telLabelGerCon.setBounds(40, 90, 80, 14);

        telTextFieldGerCon.setEditable(false);
        getContentPane().add(telTextFieldGerCon);
        telTextFieldGerCon.setBounds(40, 110, 130, 30);

        emailLabelGerCon.setText("Email");
        getContentPane().add(emailLabelGerCon);
        emailLabelGerCon.setBounds(190, 90, 200, 14);

        emailTextFieldGerCon.setEditable(false);
        getContentPane().add(emailTextFieldGerCon);
        emailTextFieldGerCon.setBounds(190, 110, 220, 30);

        respLabelGerCon.setText("Responsável");
        getContentPane().add(respLabelGerCon);
        respLabelGerCon.setBounds(450, 90, 80, 14);

        respTextFieldGerCon.setEditable(false);
        getContentPane().add(respTextFieldGerCon);
        respTextFieldGerCon.setBounds(450, 110, 150, 30);

        assuntoLabelGerCon.setText("Descrição");
        getContentPane().add(assuntoLabelGerCon);
        assuntoLabelGerCon.setBounds(40, 220, 70, 20);

        assuntoTextFieldGerCon.setEditable(false);
        assuntoTextFieldGerCon.setPreferredSize(new java.awt.Dimension(450, 30));
        getContentPane().add(assuntoTextFieldGerCon);
        assuntoTextFieldGerCon.setBounds(40, 180, 560, 30);

        lupaLabelGerCon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-32.png"))); // NOI18N
        lupaLabelGerCon1.setText("jLabel5");
        lupaLabelGerCon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaLabelGerCon1MouseClicked(evt);
            }
        });
        getContentPane().add(lupaLabelGerCon1);
        lupaLabelGerCon1.setBounds(410, 40, 30, 30);

        descriTextFieldGerCon.setEditable(false);
        descriTextFieldGerCon.setColumns(20);
        descriTextFieldGerCon.setRows(5);
        descriTextFieldGerCon.setPreferredSize(new java.awt.Dimension(450, 30));
        jScrollPane1.setViewportView(descriTextFieldGerCon);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 240, 560, 140);

        assuntoLabelGerCon1.setText("Assunto");
        getContentPane().add(assuntoLabelGerCon1);
        assuntoLabelGerCon1.setBounds(40, 150, 70, 20);

        ultimosAtendimentos.setText("Ver todos os atendimentos");
        ultimosAtendimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ultimosAtendimentosMouseClicked(evt);
            }
        });
        getContentPane().add(ultimosAtendimentos);
        ultimosAtendimentos.setBounds(410, 400, 190, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Telefone", "E-mail", "Responsavel", "Assunto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(660, 30, 500, 402);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
        });

        jMenu1.setText("Inicio");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenuSair.setText("Cadastros");

        jMenuCliente.setText("Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuCliente);

        jMenuUsuario.setText("Usuário");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuUsuario);

        jMenuAtendimento.setText("Atendimento");
        jMenuAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAtendimentoActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuAtendimento);

        jMenuBar1.add(jMenuSair);

        jMenuEditar.setText("Editar");

        jMenuEdCliente.setText("Cliente");
        jMenuEdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdClienteActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdCliente);

        jMenuEdUsuario.setText("Usuário");
        jMenuEdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdUsuarioActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdUsuario);

        jMenuEdAtendimento.setText("Atendimento");
        jMenuEdAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdAtendimentoActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuEdAtendimento);

        jMenuBar1.add(jMenuEditar);

        jMenuExibir.setText("Exibir");

        jMenuRelatorio.setText("Relatórios");
        jMenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuRelatorio);

        jMenuExConsultaAtendimento.setText("Consulta atendimento");
        jMenuExConsultaAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExConsultaAtendimentoActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuExConsultaAtendimento);

        jMenuConsultaFuncional.setText("Consulta funcional");
        jMenuConsultaFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaFuncionalActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaFuncional);

        jMenuConsultaCliente.setText("Consulta cliente");
        jMenuConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaClienteActionPerformed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaCliente);

        jMenuBar1.add(jMenuExibir);

        jMenu3Sair.setText("Sair");
        jMenu3Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3SairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3Sair);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void funcionalTextFieldGerConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionalTextFieldGerConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcionalTextFieldGerConActionPerformed

    private void clienteTextFieldGerConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTextFieldGerConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTextFieldGerConActionPerformed

    private void idAtendimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAtendimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAtendimentoTextFieldActionPerformed

    private void lupaLabelGerConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaLabelGerConMouseClicked
        if(idAtendimentoTextField.getText().length() > 0){
            String idAtendimento = idAtendimentoTextField.getText();
            int erro = 0;
            try{
                this.id_atendimento = Integer.parseInt(idAtendimento);
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "ERRO, o id_atendimento possui letras!");
                erro++;
            }
            if(erro == 0){
                Atendimento buscar = new Atendimento(null, null, null, null, "0", null);
                this.buscaAtendimento = buscar.getAtendimento(this.id_atendimento);
                if(this.buscaAtendimento == null){
                    JOptionPane.showMessageDialog(null, "Atendimento não encontrado!");
                } else {
                    String telefone = String.valueOf(this.buscaAtendimento.getTelefone());
                    descriTextFieldGerCon.setText(this.buscaAtendimento.getDescricao());
                    emailTextFieldGerCon.setText(this.buscaAtendimento.getEmail());
                    respTextFieldGerCon.setText(this.buscaAtendimento.getResponsavel());
                    telTextFieldGerCon.setText(telefone);
                    assuntoTextFieldGerCon.setText(this.buscaAtendimento.getAssunto());
                    clienteTextFieldGerCon.setText(this.buscaAtendimento.getCnpj());
                    
                    
                    javax.swing.table.DefaultTableModel dtm2 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
                    dtm2.setNumRows(0);
                    //ISSO TIRA AS LINHAS DA TABELA
                    int x=0;
                    dtm2.addRow(new Object[]{" "," "," "," "," "," "});// cada " " para cada coluna
                    jTable1.setValueAt(this.id_atendimento,x,0);
                    jTable1.setValueAt(this.buscaAtendimento.getCnpj(),x,1);
                    jTable1.setValueAt(telefone,x,2);
                    jTable1.setValueAt(this.buscaAtendimento.getEmail(),x,3);
                    jTable1.setValueAt(this.buscaAtendimento.getResponsavel(),x,4);
                    jTable1.setValueAt(this.buscaAtendimento.getAssunto(),x,5);
                }
            }
        }
    }//GEN-LAST:event_lupaLabelGerConMouseClicked

    private void lupaLabelGerCon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaLabelGerCon1MouseClicked
        Atendimento listados = new Atendimento(null, null, null, null, "0", null);
        this.cnpj = clienteTextFieldGerCon.getText();
        listados.todosOsClientes(0, this.cnpj);
        
        int tamanho = listados.listaId.size();
        
        javax.swing.table.DefaultTableModel dtm2 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        dtm2.setNumRows(0);
        //ISSO TIRA AS LINHAS DA TABELA
        int x=0;
        
        for(int i = 0; i < tamanho; i++){
            dtm2.addRow(new Object[]{" "," "," "," "," "," "});// cada " " para cada coluna
            jTable1.setValueAt(String.valueOf(listados.listaId.get(i)),x,0);
            jTable1.setValueAt(listados.listaNome.get(i),x,1);
            jTable1.setValueAt(String.valueOf(listados.listaTelefone.get(i)),x,2);
            jTable1.setValueAt(listados.listaEmail.get(i),x,3);
            jTable1.setValueAt(listados.listaResponsavel.get(i),x,4);
            jTable1.setValueAt(listados.listaAssunto.get(i),x,5);
            x++;
        }
        
    }//GEN-LAST:event_lupaLabelGerCon1MouseClicked

    private void ultimosAtendimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ultimosAtendimentosMouseClicked
        Atendimento listados = new Atendimento(null, null, null, null, "0", null);
        this.cnpj = clienteTextFieldGerCon.getText();
        listados.todosOsClientes(0, null);
        
        int tamanho = listados.listaId.size();
        
        javax.swing.table.DefaultTableModel dtm2 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        dtm2.setNumRows(0);
        //ISSO TIRA AS LINHAS DA TABELA
        int x=0;
        
        for(int i = 0; i < tamanho; i++){
            dtm2.addRow(new Object[]{" "," "," "," "," "," "});// cada " " para cada coluna
            jTable1.setValueAt(String.valueOf(listados.listaId.get(i)),x,0);
            jTable1.setValueAt(listados.listaNome.get(i),x,1);
            jTable1.setValueAt(String.valueOf(listados.listaTelefone.get(i)),x,2);
            jTable1.setValueAt(listados.listaEmail.get(i),x,3);
            jTable1.setValueAt(listados.listaResponsavel.get(i),x,4);
            jTable1.setValueAt(listados.listaAssunto.get(i),x,5);
            x++;
        }
    }//GEN-LAST:event_ultimosAtendimentosMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        new TelaInicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        new TelaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        new TelaUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAtendimentoActionPerformed
        new TelaAtendimento().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuAtendimentoActionPerformed

    private void jMenuEdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdClienteActionPerformed
        new TelaEditaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdClienteActionPerformed

    private void jMenuEdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdUsuarioActionPerformed
        new TelaEditaUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdUsuarioActionPerformed

    private void jMenuEdAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdAtendimentoActionPerformed
        new TelaAtendimentoEditar().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEdAtendimentoActionPerformed

    private void jMenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioActionPerformed
        new TelaGerenteRelatorio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuRelatorioActionPerformed

    private void jMenuExConsultaAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExConsultaAtendimentoActionPerformed
        new TelaAtendimentoConsulta().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuExConsultaAtendimentoActionPerformed

    private void jMenuConsultaFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaFuncionalActionPerformed
        new Consultar().setVisible(true);
    }//GEN-LAST:event_jMenuConsultaFuncionalActionPerformed

    private void jMenuConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaClienteActionPerformed
        new TelaConsultaCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuConsultaClienteActionPerformed

    private void jMenu3SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3SairMouseClicked
        // Botão Sair - tela principal
        System.exit(0);
    }//GEN-LAST:event_jMenu3SairMouseClicked

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendimentoConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assuntoLabelGerCon;
    private javax.swing.JLabel assuntoLabelGerCon1;
    private javax.swing.JTextField assuntoTextFieldGerCon;
    private javax.swing.JLabel clienteLabelGerCon;
    private javax.swing.JTextField clienteTextFieldGerCon;
    private javax.swing.JTextArea descriTextFieldGerCon;
    private javax.swing.JLabel emailLabelGerCon;
    private javax.swing.JTextField emailTextFieldGerCon;
    private javax.swing.JTextField funcionalTextFieldGerCon;
    private javax.swing.JLabel idAtendimento;
    private javax.swing.JTextField idAtendimentoTextField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3Sair;
    private javax.swing.JMenuItem jMenuAtendimento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuConsultaCliente;
    private javax.swing.JMenuItem jMenuConsultaFuncional;
    private javax.swing.JMenuItem jMenuEdAtendimento;
    private javax.swing.JMenuItem jMenuEdCliente;
    private javax.swing.JMenuItem jMenuEdUsuario;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuExConsultaAtendimento;
    private javax.swing.JMenu jMenuExibir;
    private javax.swing.JMenuItem jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lupaLabelGerCon;
    private javax.swing.JLabel lupaLabelGerCon1;
    private javax.swing.JLabel respLabelGerCon;
    private javax.swing.JTextField respTextFieldGerCon;
    private javax.swing.JLabel telLabelGerCon;
    private javax.swing.JTextField telTextFieldGerCon;
    private javax.swing.JButton ultimosAtendimentos;
    private javax.swing.JLabel userLabelGerCon;
    // End of variables declaration//GEN-END:variables
}
