/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import dao.*;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author XL
 */
public class TelaAtendimentoConsulta extends javax.swing.JFrame {
    
    private int id_atendimento;                                             
    private Atendimento buscaAtendimento;
    private String cnpj;
    
    
    /**
     * Creates new form TelaAtendimento
     */
    public TelaAtendimentoConsulta() {
        initComponents();
        listarTodosOsAtendimentos();
    }
    
    public void listarTodosOsAtendimentos(){
        Atendimento listados = new Atendimento(null, null, null, null, "0", null);
        this.cnpj = cliente.getText();
        listados.todosOsClientes(0, null);
        
        int tamanho = listados.listaId.size();
        
        javax.swing.table.DefaultTableModel dtm2 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        dtm2.setNumRows(0);
        //ISSO TIRA AS LINHAS DA TABELA
        int x=0;
        
        for(int i = 0; i < tamanho; i++){
            dtm2.addRow(new Object[]{" "," "," "," "," "," "});// cada " " para cada coluna
            jTable1.setValueAt(String.valueOf(listados.listaId.get(i)),x,0);
            jTable1.setValueAt(listados.listaNome.get(i),x,1);
            jTable1.setValueAt(String.valueOf(listados.listaTelefone.get(i)),x,2);
            jTable1.setValueAt(listados.listaEmail.get(i),x,3);
            jTable1.setValueAt(listados.listaResponsavel.get(i),x,4);
            jTable1.setValueAt(listados.listaAssunto.get(i),x,5);
            x++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idAtendimento = new javax.swing.JLabel();
        idAtendimentoTextField = new javax.swing.JTextField();
        clienteLabelGerCon = new javax.swing.JLabel();
        cliente = new javax.swing.JFormattedTextField();
        lupaLabelGerCon = new javax.swing.JLabel();
        userLabelGerCon = new javax.swing.JLabel();
        funcionalTextFieldGerCon = new javax.swing.JTextField();
        telLabelGerCon = new javax.swing.JLabel();
        telTextFieldGerCon = new javax.swing.JTextField();
        emailLabelGerCon = new javax.swing.JLabel();
        emailTextFieldGerCon = new javax.swing.JTextField();
        respLabelGerCon = new javax.swing.JLabel();
        respTextFieldGerCon = new javax.swing.JTextField();
        assuntoLabelGerCon = new javax.swing.JLabel();
        assuntoTextFieldGerCon = new javax.swing.JTextField();
        lupaLabelGerCon1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriTextFieldGerCon = new javax.swing.JTextArea();
        assuntoLabelGerCon1 = new javax.swing.JLabel();
        ultimosAtendimentos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        descriTextFieldGerCon1 = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuAtendimento = new javax.swing.JMenuItem();
        jMenuProblema = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuEdCliente = new javax.swing.JMenuItem();
        jMenuEdUsuario = new javax.swing.JMenuItem();
        jMenuEdAtendimento = new javax.swing.JMenuItem();
        jMenuEdProblema = new javax.swing.JMenuItem();
        jMenuExibir = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenuItem();
        jMenuExConsultaAtendimento = new javax.swing.JMenuItem();
        jMenuConsultaFuncional = new javax.swing.JMenuItem();
        jMenuConsultaCliente = new javax.swing.JMenuItem();
        jMenuConsultaUsuario = new javax.swing.JMenuItem();
        jMenuConsultaProblema = new javax.swing.JMenuItem();
        jMenu3Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chamados");
        setPreferredSize(new java.awt.Dimension(1247, 591));
        setSize(new java.awt.Dimension(1800, 800));
        getContentPane().setLayout(null);

        idAtendimento.setText("Id do atendimento");
        getContentPane().add(idAtendimento);
        idAtendimento.setBounds(40, 20, 90, 20);

        idAtendimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAtendimentoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(idAtendimentoTextField);
        idAtendimentoTextField.setBounds(40, 40, 120, 30);

        clienteLabelGerCon.setText("CNPJ Cliente");
        getContentPane().add(clienteLabelGerCon);
        clienteLabelGerCon.setBounds(210, 20, 90, 24);

        try {
            cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(cliente);
        cliente.setBounds(210, 40, 150, 30);

        lupaLabelGerCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-32.png"))); // NOI18N
        lupaLabelGerCon.setText("jLabel5");
        lupaLabelGerCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaLabelGerConMouseClicked(evt);
            }
        });
        getContentPane().add(lupaLabelGerCon);
        lupaLabelGerCon.setBounds(160, 40, 30, 30);

        userLabelGerCon.setText("Usuário");
        getContentPane().add(userLabelGerCon);
        userLabelGerCon.setBounds(450, 20, 70, 20);

        funcionalTextFieldGerCon.setEditable(false);
        funcionalTextFieldGerCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionalTextFieldGerConActionPerformed(evt);
            }
        });
        getContentPane().add(funcionalTextFieldGerCon);
        funcionalTextFieldGerCon.setBounds(450, 40, 150, 30);

        telLabelGerCon.setText("Telefone");
        getContentPane().add(telLabelGerCon);
        telLabelGerCon.setBounds(40, 90, 80, 14);

        telTextFieldGerCon.setEditable(false);
        getContentPane().add(telTextFieldGerCon);
        telTextFieldGerCon.setBounds(40, 110, 130, 30);

        emailLabelGerCon.setText("Email");
        getContentPane().add(emailLabelGerCon);
        emailLabelGerCon.setBounds(190, 90, 200, 14);

        emailTextFieldGerCon.setEditable(false);
        getContentPane().add(emailTextFieldGerCon);
        emailTextFieldGerCon.setBounds(190, 110, 220, 30);

        respLabelGerCon.setText("Responsável");
        getContentPane().add(respLabelGerCon);
        respLabelGerCon.setBounds(450, 90, 80, 14);

        respTextFieldGerCon.setEditable(false);
        getContentPane().add(respTextFieldGerCon);
        respTextFieldGerCon.setBounds(450, 110, 150, 30);

        assuntoLabelGerCon.setText("Descrição");
        getContentPane().add(assuntoLabelGerCon);
        assuntoLabelGerCon.setBounds(40, 220, 70, 20);

        assuntoTextFieldGerCon.setEditable(false);
        assuntoTextFieldGerCon.setPreferredSize(new java.awt.Dimension(450, 30));
        getContentPane().add(assuntoTextFieldGerCon);
        assuntoTextFieldGerCon.setBounds(40, 180, 320, 30);

        lupaLabelGerCon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-32.png"))); // NOI18N
        lupaLabelGerCon1.setText("jLabel5");
        lupaLabelGerCon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaLabelGerCon1MouseClicked(evt);
            }
        });
        getContentPane().add(lupaLabelGerCon1);
        lupaLabelGerCon1.setBounds(410, 40, 30, 30);

        descriTextFieldGerCon.setEditable(false);
        descriTextFieldGerCon.setColumns(20);
        descriTextFieldGerCon.setRows(5);
        descriTextFieldGerCon.setPreferredSize(new java.awt.Dimension(450, 30));
        jScrollPane1.setViewportView(descriTextFieldGerCon);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 240, 320, 140);

        assuntoLabelGerCon1.setText("Assunto");
        getContentPane().add(assuntoLabelGerCon1);
        assuntoLabelGerCon1.setBounds(40, 150, 70, 20);

        ultimosAtendimentos.setText("Ver todos os atendimentos");
        ultimosAtendimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ultimosAtendimentosMouseClicked(evt);
            }
        });
        getContentPane().add(ultimosAtendimentos);
        ultimosAtendimentos.setBounds(410, 400, 190, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Telefone", "E-mail", "Responsavel", "Assunto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(660, 30, 500, 402);

        jLabel1.setText("Solução");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 220, 60, 20);

        descriTextFieldGerCon1.setEditable(false);
        descriTextFieldGerCon1.setColumns(20);
        descriTextFieldGerCon1.setRows(5);
        descriTextFieldGerCon1.setPreferredSize(new java.awt.Dimension(450, 30));
        jScrollPane4.setViewportView(descriTextFieldGerCon1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(380, 240, 250, 140);

        jMenuBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar2MouseClicked(evt);
            }
        });

        jMenu2.setText("Inicio");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenuSair.setText("Cadastros");

        jMenuCliente.setText("Cliente");
        jMenuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuClienteMousePressed(evt);
            }
        });
        jMenuSair.add(jMenuCliente);

        jMenuUsuario.setText("Usuário");
        jMenuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuUsuarioMousePressed(evt);
            }
        });
        jMenuSair.add(jMenuUsuario);

        jMenuAtendimento.setText("Atendimento");
        jMenuAtendimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuAtendimentoMousePressed(evt);
            }
        });
        jMenuSair.add(jMenuAtendimento);

        jMenuProblema.setText("Problema");
        jMenuProblema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuProblemaMousePressed(evt);
            }
        });
        jMenuSair.add(jMenuProblema);

        jMenuBar2.add(jMenuSair);

        jMenuEditar.setText("Editar");

        jMenuEdCliente.setText("Cliente");
        jMenuEdCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuEdClienteMousePressed(evt);
            }
        });
        jMenuEditar.add(jMenuEdCliente);

        jMenuEdUsuario.setText("Usuário");
        jMenuEdUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuEdUsuarioMousePressed(evt);
            }
        });
        jMenuEditar.add(jMenuEdUsuario);

        jMenuEdAtendimento.setText("Atendimento");
        jMenuEdAtendimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuEdAtendimentoMousePressed(evt);
            }
        });
        jMenuEditar.add(jMenuEdAtendimento);

        jMenuEdProblema.setText("Problema");
        jMenuEdProblema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuEdProblemaMousePressed(evt);
            }
        });
        jMenuEditar.add(jMenuEdProblema);

        jMenuBar2.add(jMenuEditar);

        jMenuExibir.setText("Exibir");

        jMenuRelatorio.setText("Relatórios");
        jMenuRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuRelatorioMousePressed(evt);
            }
        });
        jMenuExibir.add(jMenuRelatorio);

        jMenuExConsultaAtendimento.setText("Consulta atendimento");
        jMenuExConsultaAtendimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuExConsultaAtendimentoMousePressed(evt);
            }
        });
        jMenuExibir.add(jMenuExConsultaAtendimento);

        jMenuConsultaFuncional.setText("Consulta funcional");
        jMenuConsultaFuncional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuConsultaFuncionalMousePressed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaFuncional);

        jMenuConsultaCliente.setText("Consulta cliente");
        jMenuConsultaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuConsultaClienteMousePressed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaCliente);

        jMenuConsultaUsuario.setText("Consulta usuário");
        jMenuConsultaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuConsultaUsuarioMousePressed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaUsuario);

        jMenuConsultaProblema.setText("Consulta problema");
        jMenuConsultaProblema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuConsultaProblemaMousePressed(evt);
            }
        });
        jMenuExibir.add(jMenuConsultaProblema);

        jMenuBar2.add(jMenuExibir);

        jMenu3Sair.setText("Sair");
        jMenu3Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3SairMouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu3Sair);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void funcionalTextFieldGerConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionalTextFieldGerConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcionalTextFieldGerConActionPerformed

    private void idAtendimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAtendimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAtendimentoTextFieldActionPerformed

    private void lupaLabelGerConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaLabelGerConMouseClicked
        if(idAtendimentoTextField.getText().length() > 0){
            String idAtendimento = idAtendimentoTextField.getText();
            int erro = 0;
            try{
                this.id_atendimento = Integer.parseInt(idAtendimento);
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "ERRO, o id_atendimento possui letras!");
                erro++;
            }
            if(erro == 0){
                Atendimento buscar = new Atendimento(null, null, null, null, "0", null);
                this.buscaAtendimento = buscar.getAtendimento(this.id_atendimento);
                if(this.buscaAtendimento == null){
                    JOptionPane.showMessageDialog(null, "Atendimento não encontrado!");
                } else {
                    String telefone = String.valueOf(this.buscaAtendimento.getTelefone());
                    descriTextFieldGerCon.setText(this.buscaAtendimento.getDescricao());
                    emailTextFieldGerCon.setText(this.buscaAtendimento.getEmail());
                    respTextFieldGerCon.setText(this.buscaAtendimento.getResponsavel());
                    telTextFieldGerCon.setText(telefone);
                    assuntoTextFieldGerCon.setText(this.buscaAtendimento.getAssunto());
                    cliente.setText(this.buscaAtendimento.getCnpj());
                    
                    
                    javax.swing.table.DefaultTableModel dtm2 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
                    dtm2.setNumRows(0);
                    //ISSO TIRA AS LINHAS DA TABELA
                    int x=0;
                    dtm2.addRow(new Object[]{" "," "," "," "," "," "});// cada " " para cada coluna
                    jTable1.setValueAt(this.id_atendimento,x,0);
                    jTable1.setValueAt(this.buscaAtendimento.getCnpj(),x,1);
                    jTable1.setValueAt(telefone,x,2);
                    jTable1.setValueAt(this.buscaAtendimento.getEmail(),x,3);
                    jTable1.setValueAt(this.buscaAtendimento.getResponsavel(),x,4);
                    jTable1.setValueAt(this.buscaAtendimento.getAssunto(),x,5);
                }
            }
        }
    }//GEN-LAST:event_lupaLabelGerConMouseClicked

    private void lupaLabelGerCon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaLabelGerCon1MouseClicked
        Atendimento listados = new Atendimento(null, null, null, null, "0", null);
        this.cnpj = cliente.getText();
        listados.todosOsClientes(0, this.cnpj);
        
        int tamanho = listados.listaId.size();
        
        javax.swing.table.DefaultTableModel dtm2 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        dtm2.setNumRows(0);
        //ISSO TIRA AS LINHAS DA TABELA
        int x=0;
        
        for(int i = 0; i < tamanho; i++){
            dtm2.addRow(new Object[]{" "," "," "," "," "," "});// cada " " para cada coluna
            jTable1.setValueAt(String.valueOf(listados.listaId.get(i)),x,0);
            jTable1.setValueAt(listados.listaNome.get(i),x,1);
            jTable1.setValueAt(String.valueOf(listados.listaTelefone.get(i)),x,2);
            jTable1.setValueAt(listados.listaEmail.get(i),x,3);
            jTable1.setValueAt(listados.listaResponsavel.get(i),x,4);
            jTable1.setValueAt(listados.listaAssunto.get(i),x,5);
            x++;
        }
        
    }//GEN-LAST:event_lupaLabelGerCon1MouseClicked

    private void ultimosAtendimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ultimosAtendimentosMouseClicked
        Atendimento listados = new Atendimento(null, null, null, null, "0", null);
        this.cnpj = cliente.getText();
        listados.todosOsClientes(0, null);
        
        int tamanho = listados.listaId.size();
        
        javax.swing.table.DefaultTableModel dtm2 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        dtm2.setNumRows(0);
        //ISSO TIRA AS LINHAS DA TABELA
        int x=0;
        
        for(int i = 0; i < tamanho; i++){
            dtm2.addRow(new Object[]{" "," "," "," "," "," "});// cada " " para cada coluna
            jTable1.setValueAt(String.valueOf(listados.listaId.get(i)),x,0);
            jTable1.setValueAt(listados.listaNome.get(i),x,1);
            jTable1.setValueAt(String.valueOf(listados.listaTelefone.get(i)),x,2);
            jTable1.setValueAt(listados.listaEmail.get(i),x,3);
            jTable1.setValueAt(listados.listaResponsavel.get(i),x,4);
            jTable1.setValueAt(listados.listaAssunto.get(i),x,5);
            x++;
        }
    }//GEN-LAST:event_ultimosAtendimentosMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        new TelaInicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        new TelaInicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu3SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3SairMouseClicked
        // Botão Sair - tela principal
        System.exit(0);
    }//GEN-LAST:event_jMenu3SairMouseClicked

    private void jMenuBar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar2MouseClicked

    private void jMenuConsultaUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConsultaUsuarioMousePressed
        String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente") || tipodeusuario.equals("Tecnico")){
            new TelaConsultaUsuario().setVisible(true);
            dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes e Tecnicos!");
        }
    }//GEN-LAST:event_jMenuConsultaUsuarioMousePressed

    private void jMenuConsultaProblemaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConsultaProblemaMousePressed
       new TelaConsultaProblema().setVisible(true);
       dispose();
    }//GEN-LAST:event_jMenuConsultaProblemaMousePressed

    private void jMenuClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuClienteMousePressed
        String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente") || tipodeusuario.equals("Atendente")){
           new TelaCliente().setVisible(true);
           dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes e Atendentes!");
        }
    }//GEN-LAST:event_jMenuClienteMousePressed

    private void jMenuUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuUsuarioMousePressed
        String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente") || tipodeusuario.equals("Atendente")){
           new TelaUser().setVisible(true);
           dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes e Atendentes!");
        }
    }//GEN-LAST:event_jMenuUsuarioMousePressed

    private void jMenuAtendimentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAtendimentoMousePressed
        String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente") || tipodeusuario.equals("Atendente")){
           new TelaAtendimento().setVisible(true);
           dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes e Atendentes!");
        }
    }//GEN-LAST:event_jMenuAtendimentoMousePressed

    private void jMenuProblemaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuProblemaMousePressed
        String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente") || tipodeusuario.equals("Atendente")){
           new TelaProblema().setVisible(true);
           dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes e Atendentes!");
        }
    }//GEN-LAST:event_jMenuProblemaMousePressed

    private void jMenuEdClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEdClienteMousePressed
        String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente") || tipodeusuario.equals("Tecnico")){
           new TelaEditaCliente().setVisible(true);
           dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes e Tecnicos!");
        }
    }//GEN-LAST:event_jMenuEdClienteMousePressed

    private void jMenuEdUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEdUsuarioMousePressed
        String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente") || tipodeusuario.equals("Tecnico")){
           new TelaEditaUsuario().setVisible(true);
           dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes e Tecnicos!");
        }
    }//GEN-LAST:event_jMenuEdUsuarioMousePressed

    private void jMenuEdAtendimentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEdAtendimentoMousePressed
        String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente") || tipodeusuario.equals("Tecnico")){
           new TelaAtendimentoEditar().setVisible(true);
           dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes e Tecnicos!");
        }
    }//GEN-LAST:event_jMenuEdAtendimentoMousePressed

    private void jMenuEdProblemaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEdProblemaMousePressed
        String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente") || tipodeusuario.equals("Tecnico")){
           new TelaEditaProblema().setVisible(true);
           dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes e tecnicos!");
        }
    }//GEN-LAST:event_jMenuEdProblemaMousePressed

    private void jMenuRelatorioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRelatorioMousePressed
        String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente")){
           new TelaGerenteRelatorio().setVisible(true);
           dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes!");
        }
    }//GEN-LAST:event_jMenuRelatorioMousePressed

    private void jMenuExConsultaAtendimentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExConsultaAtendimentoMousePressed
        String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente") || tipodeusuario.equals("Tecnico")){
           new TelaAtendimentoConsulta().setVisible(true);
           dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes e Tecnicos!");
        }
    }//GEN-LAST:event_jMenuExConsultaAtendimentoMousePressed

    private void jMenuConsultaFuncionalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConsultaFuncionalMousePressed
      new Consultar().setVisible(true);
    }//GEN-LAST:event_jMenuConsultaFuncionalMousePressed

    private void jMenuConsultaClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConsultaClienteMousePressed
         String tipodeusuario = Sessao.getInstance().getUsuario().getTipo_de_usuario();
        if(tipodeusuario.equals("Gerente") || tipodeusuario.equals("Tecnico")){
           new TelaConsultaCliente().setVisible(true);
           dispose();
        } else {
           JOptionPane.showMessageDialog(null, "Apenas Gerentes e Tecnicos!");
        }
    }//GEN-LAST:event_jMenuConsultaClienteMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendimentoConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assuntoLabelGerCon;
    private javax.swing.JLabel assuntoLabelGerCon1;
    private javax.swing.JTextField assuntoTextFieldGerCon;
    private javax.swing.JFormattedTextField cliente;
    private javax.swing.JLabel clienteLabelGerCon;
    private javax.swing.JTextArea descriTextFieldGerCon;
    private javax.swing.JTextArea descriTextFieldGerCon1;
    private javax.swing.JLabel emailLabelGerCon;
    private javax.swing.JTextField emailTextFieldGerCon;
    private javax.swing.JTextField funcionalTextFieldGerCon;
    private javax.swing.JLabel idAtendimento;
    private javax.swing.JTextField idAtendimentoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3Sair;
    private javax.swing.JMenuItem jMenuAtendimento;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuConsultaCliente;
    private javax.swing.JMenuItem jMenuConsultaFuncional;
    private javax.swing.JMenuItem jMenuConsultaProblema;
    private javax.swing.JMenuItem jMenuConsultaUsuario;
    private javax.swing.JMenuItem jMenuEdAtendimento;
    private javax.swing.JMenuItem jMenuEdCliente;
    private javax.swing.JMenuItem jMenuEdProblema;
    private javax.swing.JMenuItem jMenuEdUsuario;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuExConsultaAtendimento;
    private javax.swing.JMenu jMenuExibir;
    private javax.swing.JMenuItem jMenuProblema;
    private javax.swing.JMenuItem jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lupaLabelGerCon;
    private javax.swing.JLabel lupaLabelGerCon1;
    private javax.swing.JLabel respLabelGerCon;
    private javax.swing.JTextField respTextFieldGerCon;
    private javax.swing.JLabel telLabelGerCon;
    private javax.swing.JTextField telTextFieldGerCon;
    private javax.swing.JButton ultimosAtendimentos;
    private javax.swing.JLabel userLabelGerCon;
    // End of variables declaration//GEN-END:variables
}
